#+TITLE: Misterduncan's May Days-4
 
URL: https://www.youtube.com/watch?v=4GVxduV4FQY

IMPORTANT MESSAGE

We would like to warn all viewers that today's lesson contains some strong language. There are some naughty words in this lesson.

You have been warned.

Oh hello there! Welcome to another one of my "May Days". This is a special series of English lessons for the month of May. Why May? I hear you ask. Why not? is my reply. As you can see the sun is out today and it really feels quite balmy, which means "mild", "pleasant" and temperate". Not to be confused with the word "barmy", which can mean "crazy", "mad", "daft" and... silly. Okay, perhaps I'm a little silly sometimes, but there's nothing wrong with a little silliness now and again. It keeps you young you know! This mild sunny weather is great to be out in, but the downside is that it also brings out the insects, which can sometimes be a real buzzing pain. especially if you are trying to eat "al fresco" style. Which means "outdoors". Well I suppose I shouldn't complain, at least it's not raining. 

In my May 4th lesson, I used the word "pants" to describe the last three Star Wars films. I have been asked to explain the use of this word. Well, if something is seen as not being good or worthy of praise, or if something has let you down, then we can say that it was "pants". The thing you saw or experienced left you feeling disappointed. Your feelings towards the thing are negative. Using the word "pants" is how your express this dislike. The term is chiefly used in British English. It is worth noting that in American English "pants" are actually trousers, while in British English, "pants" means underwear. Hence its negative use. We can also say that something is "a pile of pants". This also has the same (negative) meaning. To say that something is "terrible", "auful", "rubbish". "It's a pile of pants." 

I have received an e-mail from Morela from Argentina, and asks what the words "troll" and "trolling" mean. In its original form, the word "troll" is a noun for a type of cave dwelling creature from folklore (myth/legend) that is depicted as either a dwarf or giant. These creature do not really exist, but stories about them have been told through the ages so often, that they appear to be real. "Troll" can also be a verb, meaning to hunt or search tirelessly for something. Over recent years the word "troll" as a noun means a person who uses abusive language and hate speech towards others over the internet with the intention of creating an angry reaction. This is usually done anonymously. Then there is "trolling" which relates to the act of sending abusive messages to others through the internet. Most internet users see "trolling" as a form of bulling and over recent years there have been many attempts to stop if. 

Guess what is in the field at the back of my house? If you remember last year there were sheep grazing just over there. Well this year there are... bulls in the field. Yes, just a few days aga, a herd of bullocks were left. Needless to say they are quite different to sheep. They are larger, more aggressive... and their poop is huge. Really... their poop is the size of a dustbin lid. There are some phrases and idioms in English that use the word "bull". For example... 
"Take the bull by the horns" To go ahead and do something that might be dangerous or create a negative consequence. If you have been putting something off, then it might be time to take the bull by the horns and do it. 

"Cock and bull story"
A story that seems implausible and unlikely. An exaggerated story might be described as being "all cock and bull". A cock and bull story is one that cannot be believed. 

"A bull in a china shop"
To do something in an aggressive and clumsy manner. To recklessly overreact to something and create a huge fuss. "He stormed into his boss's office like a bull in a china shop."

"Bullshit"
A vulgar swear word that means stupid or untrue speech. Something which is being said that has no element of truth in it can be described as "bullshit". As a verb the word "bullshitting" is the action of talking rubbish and coming out with untrue things. The person doing this can be described as a "bullshitter". "His whole speech was nothing but bullshit." "Just stop bullshitting me and tell me the truth!" We can also say that that something is "a load of bull", or that they are "talking bull". 

"Bullish"
To be "bullish means that you are being aggressively enthusiastic and forcefully positive about something. You force your ideas onto others in a strong way. You are "bullish". You behave in a "bullish" way. It is worth remembering that in American English, "bullish" can mean "idiotic", "stupid" and "oaf like". In finance, "bullish" means that share prices are rising. The value of shares are rising. "The stock market was bullish today." 

Give me a big smile. Go on, don't be shy. Aren't teeth great? They allow us to bite and... chew our food. They even help us to form words when speaking. We tend to take our teeth for granted. We never think much about them until they start falling out. If a person loses their teeth, then they can have fake ones fitted. These are called "false teeth" or "dentures". A single tooth can be replaced if it has gone bad or rotten. I have one in my mouth. One of my front teeth is not real. It has been rebuilt using a material that looks similar to the original tooth. This is called a "crown". The artificial tooth is slotted into place over a piece of metal or part of the original tooth. The part of the tooth which can be seen is called "enamel". It is the hardest substance in the human body. Sadly it is not resistant to sugary acids contained in many types of food. Over time the enamel can be eaten away by these acides. Did you know that the state of your teeth can also affect your overall health? Poor dental hygiene has been linked to various illnesses, including heart disease and diabetes. So looking after your teeth not only allows you to keep that wonderful smile, it can also help you to stay healthy. 

In the loast "May days" lesson I showed you my lovely T-shirt. I asked you to guess how old that T-shirt is. I did give you a small clue by saying that I bought it during my youth. So how old is it? Just how antique is my T-shirt? The age of my "Pet Shop Boys" T-shirt is... 27 years! Yes, I bought the T-shirt in 1987, when I was a mere 22 years old. That was the your when construction of the "Channel Tunnel" began. Margaret Thatcher was elected Prime Minister for the third time. The human population of Earth reached five billion. Ronald Reagen was the President of the USA. "The Simpsons" appeared on our TV screens for the first time and one of the biggest movies to come out in 1987 was "three men and a baby".

I hope you have enjoyed today's "May Days" lesson and that you will join me again soon for another one. We are over half way through the month now, so there will not be many more of these lessons to come. But don't worry, there will be plenty of new English video lessons coming your way throughout the rest of the year, so keep a look out for them. If you have missed any of my "May Days" lessons then you can catch them on the playlist. This is Misterduncan in England on a bright sunny May afternoon saying... Thank you for watching me, teaching you and of course... ta-ta for now.
