#+TITLE: Misterduncan's May Days-1
 
URL: https://www.youtube.com/watch?v=dafZjnkufUE

Welcome to the first day of May and the start of "Misterduncan's May Days". I thought it would be nice to start the series off in a colourful place. And they don't come much more coloourful and bright... as here. The field you can see behind me is full of rapeseed. It is a type of plant used for the production of certain types of oil. The oil produced can be used for cooking and as a type of fuel. The oil is obtained from the rapeseeds themselves. The plants you can see here are not ready for harvesting, as the seeds have not yet formed. Rapeseed oil is now widely produced in the world. Countries with the most production include Canada and China. The production of repeseed oil here in the UK has increased steadily over the past 10 years or so. It really is a beautiful sight and it is hard to escape the feeling that summer is on its way. 


I really love receiving your comments and questions and I'm often asked to explain the meaning and use of certain words and phrases. So during May I thought it would be a good idea to answer some of those questions. For example - I have received a message from Marietta, who lives in Italy. The question is... What does the word "Doozy" mean? It seems to be used a lot in American TV shows and movies. Well Marrietta... the word "doozy" is a noun that states that something is unique or outstanding. It is an informal way of waying that something is extraordinary. The word "doozy" is used mostly in American English. "Look out for that hole, it's a doozy." "Better take an umbrella, that storm is going to be a doozy." The word is used in the movie "Groundhog Day" to describe a sidewalk step that leads to a very deep puddle of water. "Watch out for that first step, it's a doozy". 


Another word that I have been asked to define is "Sedentary". This word is an adjective that describes a person who is inactive or sits still for long periods of time. It can describe a job that involves little movement. A sedentary job is one where a person is seated. Examples of sedentary jobs include an office worker or a bus driver. It can also mean to be seated or sat down. To work while seated means that you have a sedentary job. The word can also be used in zoology to describe an animal that lives its whole life in one place and never migrates. If you have a word that you would like me to explain, then feel free send it to me. Me e-mail address will be coming up at the end of this May Day lesson.


Did you enjoy my Penang lesson? For those who did not see it, it was the lesson where I went to Penang in Malaysia. It is Lesson 67. During that lesson I went up to the top of Penang Hill on something called a funicular railway. It takes around ten minutes to get all the way up, but right now we are going to do it in just one minute. With the help of some video trickery. Do you want to take a ride? You'd better hold on tight because... here we go! Oh my goodness...that was quite a journey. Imagine what it would be like if the train really moved that fast. It would be a "white knuckle ride". The phrase "white knuckle ride" relates to an exciting or frightening experience while moving fast or high up...or both, in a certain direction. A bumpy plane journey or a dangerously fast car ride could be described as a "white knuckle ride". The phrase relates to the colour of the knuckles of your hands while they are clenched or gripping tightly to something. 


I hope you have enjoyed this first day of May and that you will join me for another very soon. There will be many more of them to come during this month. From a bright and sunny England...this is Misterduncan saying thanks for watching me, teaching you... and of course...ta-ta for now.
