#+TITLE: Advanced English

** Lesson 1 Let's Visit New York!

New York, New York. The city so nice they named it twice. 

These words were used to describe New York When it was by far the largest, richest, and most developed city in the United States．New York still remains the largest and most famous city in the U.S. today, but some of its "nice" reputation has fallen over the past thirty years with stories of rampant crime making headlines around the world. How true are these stories? Is New York still a "nice" place to visit? If so, what can a tourist do in New York? Let's take a closer look at America's premier city.

First, as personal and social security are always uppermost in the minds of travelers, just how "dangerous" a city is New York? Despite the glaring headlines, New York, located in the northeastern U.S., is one of the safest cities in the U.S. In fact, New York states (which include New York city thus, "New York, New York, the city so nice they named it twice") ranks below other big-population States like California in both violent crime (of much concern to the tourist) and property crime. Other major cites have higher crime rates, too. Thus, the foreign traveler to New York City can feel more secure here than in most other large metropolitan areas of the U.S. besides safety, why do more foreigners visit New York than any other American city? The answer lies in the character of New York itself. No other city in the world is more cosmopolitan. A walk through its hundreds of residential neighborhoods is like walking around the world itself. Place names like Chinatown and little Italy can be found on any map of New York, but smaller ethnic neighborhoods also abound. Also, all these groups sponsor annual or seasonal festivals, so that nearly every week one or more of these peoples will share their cultural experiences (and food!) with other New Yorkers.

Because of this unsurpassed ethnic diversity, the restaurant goer will feel that he has died and gone to heaven while in New York. There is hardly a cuisine on the planet that is not represented here. Even better, many of these exotic restaurants are reasonably priced. One is never far from a restaurant in New York. There are thousands of Chinese restaurants alone.

Besides the internationally famous sight-seeing attractions-mostly in the borough (district ) of Manhattan--such as the Statue of Liberty, the world trade center with its two 110-story towers, Wall Street, the United Nations, and Broadway, many other interesting places await the curious traveler. The Bronx Zoo in the northern borough of the Bronx is one of the world’s best. The borough of Queens offers a great variety of ethnic residential neighborhoods. Brooklyn contains the Botanical Gardens, Coney Island (a beach with an amusement Park), and J. F. K. International Airport. Finally, Staten Island, the smallest borough, still affords a Look at what New York used to be like, including a farm!

For culture lovers, New York has more museums than any other city, but some of these are not internationally known. A visit to any of these historical, technical, ethnic, or academic museums is well worth the time. New York's art, music, dance, and fashion scenes are a mecca for the young and professional alike. The Internet website for specific information on New York City and state tourists is www.iloveny.state.ny.us. A toll-free number for tourists already in the U. S. or Canada is also available at 1-800-call-NYS.

No matter what your interest is, if it can be found in an urban environment, it can be found in New York. Its eight million citizens hail from every corner of the globe, but they are united in the love of their challenging but rewarding city. As the locals there say, 'Sure, you have to be a little crazy to live in New York, but you'd be nuts to live anywhere else!"


** Lesson 2 The Amish

In the land of rock and roll, the space shuttle, and computerized living, who could imagine that about 50,000 Americans do not use telephones, electric lights, or cars, not because they are poor, but out of choice? As hard as this may be to imagine, the Amish, or more properly, the Amish Mennonites, still live a traditional, rural lifestyle direct from 17th century Europe!

To understand these unique Americans better, it is necessary to understand their history. Beginning with the revolution started by Martin Luther, leader of the Protestant Reformation in Germany in the 16th century, Europe was wracked by religious wars for several hundred years. Modern Europe is a product of these wars and of the political and religious philosophies of those times. The main figures in this tragic period were the Roman Catholic Church and the Protestants, those who rebelled against papal rule from Rome. Among the thousands of splinter groups formed outside of Rome's religious rule were the Mennonites, a group of particularly conservative, rural Christians situated in what is today Switzerland, part of eastern France, and southern Germany.

To make a long story short, the Mennonite Amish were so conservative that they made more enemies than fiends. In order to preserve their peculiar lifestyle, they began to immigrate to the British colonies in North America in about 1720 (before Canada and the United States were formed as independent countries). There they found the religious freedom they had sought. Amish settlements sprang up in the colonies and territories of Pennsylvania, Ohio & Indiana as well as in Ontario, in what is today Canada. Surprisingly, there are no Amish groups today in Europe.

Little has changed about their lifestyle since then. Just how conservative are the Amish? A group of Amish looks like a cast from a biblical movie set. All the men wear large brimmed black hats, beards (but not mustaches), and clothes made by their wives. The women wear a hair covering called a bonnet, long dresses, and black shoes. Even though all Amish men and women marry, you will not see a wedding ring, for even this simplest type of jewelry is banned among them. The Amish are primarily farmers, and good ones, despite the fact that they do not use modern farm machinery. Their children are educated in local primary schools, but secondary education is in the home. Sundays are spent mostly in church. An old dialect of German mixed with English is used in church and at home. Their lives are uncomplicated and few Amish leave their homes to enter the mainstream American society.

Rural Pennsylvania where most of the Amish live is beautiful countryside. If you have the opportunity to drive through the gentle, rolling hills amidst lush farmlands, perhaps you will see a horse and buggy driven by a family dressed mostly in black. These are the Amish, an enduring and endearing people.


** Lesson 3 Indoor Pollution

So you think that by staying at home you are safe from all the terrible kinds of pollution present outdoors, such as in or near factories, roads, and garbage dumps? Do you think that by staying in your office you are breathing cleaner, safer air than when you go outside for lunch or are on the way back home from work? Think again. Recent research done at the University of Texas has shown that staying indoors may actually be more harmful to one's health than being outdoors even in smoggy cities.

Apparently, we are safe neither at home nor in the business office. We use water in both places, but the above-mentioned research shows that chemicals added to our local water supply to kill harmful bacteria can have unwanted side effects. These chemicals can cause potential harm through drinking and in seemingly harmless activities as cleaning one's house. These additives are released from water by daily actions like water running out of faucets, spraying from garden hoses, or splashing in dishwashers and washing machines. As the water is agitated, these chemicals are released into the air and then breathed in. Once inside our bodies, they start to affect our health adversely.

Does this mean we should stop bathing? No, say the scientists, but we should put all pollution into perspective. Activities at home such as the burning of propane, coal, cooking oil, or even candles and incense release carbon monoxide and particulates such as soot which have been proven as harmful to health as working or living near high density traffic. New rugs, bedding, and even clothing give off that "new smell," which is a sure sign of chemicals. In the office, newly applied paint, newly purchased telephones and other telecommunications equipment, and computers and their peripherals release polluting chemicals, too. As offices and homes often have inadequate ventilation, these chemicals can build up to become health nuisances. Their toxic effects are only now being slowly recognized.

These facts suggest that, at a minimum, proper airing of newly purchased goods with an obvious chemical smell is a wise precaution. Home and office windows should be opened during good weather to allow a flushing of stale air. Even one's car need to be ventilated as well as the garage.

We need further research to understand better other potential health hazards, too. For example, the effect of overcrowding of schools (carbon dioxide build up), factory work environments (an endless list of potentially dangerous substances), and even home heating and cooling (the furnace and air conditioner may be our enemies, not our fiends) have only recently started to come to light. Until we understand the effects of our new technological environment better, we can only hope that "there is no place like home."


** Lesson 4 Pizzas, Please!

One of the world's most popular foods along with the hamburger, fried chicken, and milk shakes is pizza. Although the origin of the first three foods is well understood, that of pizza until recently, anyway was for a long time an international controversy.

The word pizza has always been known to mean pie or cake, and is an Italian word. This fact alone might suggest pizza's origins. However, some years ago in New York City, a Chinese restaurateur challenged the Italian ethnicity of pizza by declaring that pizza was originally a Chinese food. But was then taken along with pasta by Marco Polo back to Italy. It seemed the question would never be solved.

The case actually made itself into court (only in America!). Italian restaurateur challenged the Chinese businessman's view, but when all the evidence was in, the result was announced by a judge, as early as the Roman Empire, pizza was baked in ovens there and eaten. Chinese normally steam or fry their foods, not bake them. Bread and other baked goods to which pizza belongs were developed from India through Europe where they are still enjoyed today. Besides, cheese is an essential element of pizza, and the Chinese traditionally did not produce cheese. The case was closed, and pizza's paternity has now been established.

For pizza lovers, of course, their favorite food might have been invented in Argentina or Indonesia. Who cares? Indeed, pizza has changed as it has spread around the globe, so that when ordering a pizza in Honolulu, New York, Paris, Istanbul, New Delhi, or Tokyo, you are sure to receive a slightly different version in each city or country. Pizza known to Italians and New Yorkers (Where pizza was first introduced into the United States by the many Italian Americans living there) is a round, thin crusted baked dish covered with tomato sauce and cheese. To improve the taste, pieces of Italian sausages such as pepperoni and salami, and vegetables like onions, green peppers and olives are added. Occasionally, anchovies, small, salty fish, are also used. However, Asians enjoy pizza with corn, cucumbers, and other vegetables, not to mention assorted seafood. Hawaiians, perhaps predictably, developed a pizza with a pineapple and ham topping. Today, nearly every country has its favorite local variety of pizza. Worldwide, there must be more than 1 000 varieties of pizza.

Some people are not so fond of pizza. They classify it as a junk food, along with greasy French fries, potato chips, and hamburgers. On the contrary, said defenders of pizza, it is indeed a healthful food. Carefully chosen fresh ingredients can ensure the quality of any food we eat, and pizza is no exception. 

Others protest that pizza is too fattening to be eaten regularly. Not true, respond those enamored of pizza's charms. It all depends on the ingredients and how well they are prepared. For example, the meats which are used as toppings on pizza are often first fried to remove excess fat. The cheeses used can be selected for their high protein but low milk fat. Sparse rather than generous addition of spices such as salt ensure that pizza need not be considered junk food. A well-made pizza not only looks, smells, and tastes great, but it is a wise choice for everyone as a regular food source. Indeed, It seems the only disadvantage to pizza is that when dropped, it causes a mess!

Children enjoy pizza because it's fun to eat and delicious. Workers enjoy it because it is inexpensive and quick to order, too. Families enjoy the convenience of carrying home a whole meal from the many vendors of this world famous food. With its many advantages, no one needs to resist the allure of one of the world's most popular foods. Come to think of it, let's have pizza for dinner tonight!


** Lesson 5 Hot Animals around the World: Chameleons

Every few months this program will feature an animal which has caught the eye of the world's public to become a favorite or "hot" animal. In the first of this unusual series, we will look at the chameleon, one of nature's strangest creatures. 

Perhaps no other group of animals has caught mankind's imagination like reptiles. Among the several subclasses (or "orders" in biology) of reptiles are snakes and lizards, turtles and tortoises, crocodiles and alligators, and the tuatara, a marine lizard in New Zealand. The dinosaurs, too, belonged to the class of reptile. Was it a snake, lizard, or crocodile that caught the fancy of some Chinese in times gone by to create the dragon? A perennial theme, reptiles have been featured over the past ten years in box-office hits and bombs alike as dinosaurs (Jurassic Park and The lost World), crocodiles, and snakes (Anaconda). Though not nearly as large as these mighty reptiles, the lowly chameleon nonetheless has amazed countless generations with its special talents and skills. 

What is a chameleon? Its unusual name fits this unusual animal perfectly, for it translates from the ancient Greek as "lion on the ground." This is unexpected, since chameleons spend most of their time in trees, and as for looking like a lion, a chameleon looks like a ... well, a chameleon! No other animal in Nature's zoo looks quite as bizarre as they do. Where do they live? True chameleons are found only in the tropical forests and jungles of the Old World, and nearly half of its species live on the African island of Madagascar. 

What's special about the chameleon? Plenty! From its tongue to its tail the chameleon offers a storehouse of specialties. The tongue of this modem-day dinosaur look-alike can be extended more than twice the length of its body. This type of tongue, also present in frogs and toads, is called an extensile tongue. The eyes of the chameleon are even more remarkable. Its eyes are turreted and can be moved independently so that it can view two different objects simultaneously! This comes in especially handy as it is tree dwelling. The chameleon can keep one eye on its prey and the other on its footing. Its head is often helmet-shaped, and some species have horn-like structures growing out of this scaly helmet. 

The feet and tail of the chameleon are also special. Both are prehensile; that is, they are both perfectly adapted to their sylvan environment. The toes of the chameleon's feet are bunched into inside and outside groups of two or three to enable this reptile to grasp tree branches tightly. The chameleon can thus climb extraordinarily well while using its tail to grab objects for further balance. 

The above inventory of natural selection specializations would be remarkable enough, but what really separates the chameleon from its fellow reptiles is the fact that its scales contain the ability to change color, Though many people think the chameleon can change its color at will and that it can blend into any color, these are misconceptions. In fact, chameleons can blend into many natural colors and even patterns, but they cannot do this at will. Instead, this happens naturally according to temperature, emotional state of the animal, and the triggering of certain hormones within its body. 

It is hard to imagine an animal more interesting than the chameleon, with its weird appearance and special abilities. We should always remember, however, that these animals require their native habitat to flourish in, not zoos or individuals' terrariums. If you want your grandchildren to see this gift of nature, do not collect it as a pet. These natural treasures evolved over millions of years without mankind's help; they will continue to survive better if left alone.


** Lesson 6 Table Manners in Anglo-America

"Oh, no! Here I am at an American family's home at the dinner table. There are all kinds of plates, saucers, cups, and silverware at my place. Which should I use for which food? Should I sit down first or wait for the host to invite me? Should I have brought a gift? Someone please tell me what to do! " 

Have you ever been in or had a nightmare about this situation? Don't worry! This article will help steer you through the rocks and reefs of Anglo-American table manners so that if you are ever abroad in Canada or the United States, or at someone's home from one of those countries, you will feel right at home. 

It is important to distinguish what kind of occasion you will be attending before you plan for a pleasant evening. Most Anglo-Americans enjoy entertaining at home, but they don't enjoy stuffy, formal dinners. They invite their friends over for a fun evening, not as a test of one's knowledge of cultural traditions. If, however, you are invited to a formal affair, such as a so-called "sit-down" dinner, you may want to know in advance some basic rules of "black tie" etiquette. 
The first thing to remember when attending a dinner at a Western home is that you are the guest and that you are a foreigner. No one will invite you if he does not really want you to enter his "castle." so you can be sure that you are wanted. Additionally, as you do not come from the same country or culture as your host, he or she or they will surely be aware of this, and will be very forgiving if you unintentionally do or say something which would otherwise offend them. Keeping these two simple tips in mind should greatly ease your concern about being present at a dinner in someone else's home. 

Before arriving at your host's home, you may want to make sure of three things. First, be a few minutes late, say, about five to ten minutes if possible. Never be early, as the host may not have everything prepared yet. Nor should you be more than 20 minutes late. Your host may begin to worry about whether you are able to attend the dinner or not. Next, as to whether to bring a gift, in most informal gatherings, it is not necessary. If you like, you can bring some fruit or sweets, or, especially if there is a hostess, some flowers. These are thoughtful, cheerful gifts sure to please. Do not bring alcoholic beverages unless you are sure of your host's or hostess's preferences in drinks. Above all, do not spend a lot of money, and never give money. As we say in English, "it's the thought that counts." Finally, wear comfortable clothing. One can overdress as well as appear sloppy. For a special occasion or religious holiday, such as a retirement party or Christmas, a tie and jacket would be suitable for the gentlemen and a dress or sweater and skirt for the ladies. 

For more formal affairs, you will probably be told what to wear, such as "formal dress requested," etc. A tie and jacket or tuxedo for the gents and an evening gown for the ladies would be in order here. If you are unsure what to wear, you can always ask the host. Gifts are seldom appropriate for these affairs, unless for a wedding reception, at which gifts are more customary than cash. 

Your host in his home will usually motion you where to sit. At formal gatherings, name cards are sometimes provided, or you will be told where to sit. Do not be alarmed by a great deal of cutlery: simply start from the outside and work your way in. Formal affairs often have several courses of food with the appropriate cutlery for each dish. There is no harm in checking with your neighbor to see what implement he is using. After all, "When in Rome, do as the Romans do." It is customary to ask others to pass dishes to you for self-serving; at a formal dinner party, there is usually catering (service). Again, do not hesitate to ask others for information or advice. They are usually pleased to help you. 

The most important piece of advice is this: enjoy yourself. No host enjoys seeing nervous or fearful guests who are struggling to "do the right thing" at his home or expensive formal dinner party. Watch others or ask for their advice, and join in the conversation and good times as best you can. If you do, after the first such evening out, you will certainly look forward to the next!


** Lesson 7 The Delights of South Island

One of the odder coincidences of physical geography is the fact that there are two double islands, roughly the same size, positioned at each other's antipodes, or farthest-distant point. The islands of England and Ireland in the Northern Hemisphere and the islands of North Island and South Island in the southern Hemisphere are just such a coincidence. The first two islands comprise the United Kingdom and the Republic of Ireland (or Eire), and the second two islands comprise New Zealand. Among these four islands, there can be no doubt that South Island is the least polluted and most spectacularly scenic of them all. 

There is much competition to make such a claim. The island of England, politically constituting England, Scotland, and Wales of the United Kingdom, is dotted with country villages set alongside rivers and lakes. There are not very tall but nonetheless rugged mountains in the north, and endless miles of rocky coastline that seem mystical. Ireland, too, is a paradise of greenery, with far fewer people than populous England and even more quaint villages scattered among its low-lying hills and forever green fields. North Island in New Zealand sports a balmy climate and the beaches to make use of it; one beach alone is more than 150 kilometers long and with relatively few people on its shores, one can pretend one is at the very end of the earth. Volcanoes, large lakes, and quickly flowing rivers traverse the land. Given the beauty of these three islands, what makes South Island so special? 

Plenty. For those who like mountains, South Island is sure to please. Mt. Cook at 3764 meters is its highest peak, with 16 others above 3000 meters. Naturally, many local and foreign mountain climbers come here for the challenge of these Southern Alps. In addition, there is an extensive glacier system, endless forests, and innumerable lakes throughout this highland area. Some of the world's best mountain scenery is available within the 500-kilometer long chain of the Southern Alps. 

Perhaps you prefer the sea? South Island is not only an island, but many tiny islets can be found off its coastline. Great deep-sea fishing, scuba diving, and snorkeling can be had, though the waters here are cooler than those of North Island. (Remember, in the Southern Hemisphere, as we go north, it gets warmer.) As fewer people live on South Island than on North Island, those who crave solitude and pristine beaches will be amazed at their luck here. With almost no heavy industry on South Island, the air, water, and land are all free of pollution. The Local seafood is therefore clean, plentiful, and never-ending. 

Do healthful climates interest you? South Island is the place to be. Its temperate climate sees little snow except in the highlands and mountainous areas. Like Ireland and England, there are no extremes of temperature, either. Summers are warm, not hot, and winters are brisk rather than freezing. The fresh air is sometimes humid from the abundant rainfall of this area. Every season invites the nature lover to get out and be active in the countryside. 

Of course, South Island is not for everyone. For those who need busy, crowded, noisy, and polluted cities, this Southern outpost will surely disappoint. For those who enjoy pressure and stress, South Island will leave them empty-handed. And for those who would rather stay at home or in an office in front of a computer screen or in the thumping, smoke-filled dance floors of discos, some of the world's best natural scenery will never entice them away. For the rest of us, though, South Island is the world's best kept secret. If Nature's paradise sounds alluring, make a point of visiting South Island.


** Lesson 8 Ireland's Contribution to English

Nearly everyone knows that countries such as the United Kingdom, the United States of America, Canada, Australia, and New Zealand are primarily English-speaking countries; that is, English is the mother tongue used in these countries. What is less well known is that English is also the mother tongue in countries such as the Republic of Ireland (officially called Eire), Barbados, Jamaica, Trinidad, and Guyana. Among these latter few, the Irish have made contributions to the English language in both its lexicon and literature which can be considered second to none. 

Virtually every aspect of English literature has been graced by the writings of the Irish. This fact is all the more amazing because Ireland is a relatively small country, with never more than four million people throughout its long history. Yet many great "English" writers were indeed born and often raised in Ireland, though many, too, immigrated to the United Kingdom at some point in their lives. Among these pillars of English literature were Jonathan Swift, William Butler Yeats, James Joyce, Samuel Beckett, Oscar Wilde, George Bernard Shaw, and Edmund Burke. Many other lesser-known figures have punctuated English literature as well. These men's contributions to the English language and to Western thought in general are immeasurable. A review of two of these writers' major works will reveal why. 

Jonathan Swift (1667 -1745) by most reckoning is the best English-language satirist ever, and one of the world's greatest as well. Born in Ireland of English parents, Swift went to school there through his bachelor's degree (Trinity College, Dublin, capital of Ireland). Thereafter he frequently traveled between England and Ireland, including years spent at Oxford College, where he earned his master's degree. Swift wrote a great deal of poetry, but he is best regarded as a prose satirist. He wrote prolifically both in Ireland and England, nearly constantly shuttling from one to the other. In Ireland he worked on Gulliver's Travels, which he later had published in England in 1726. Already famous by that time, Swift would become immortalized with this last great work. What child does not know the story of the brave sailor Gulliver as he travels through lands in which he is at turn both a giant and a midget? Yet most readers are not aware of Swift's intent to satirize the political, academic, and religious leaders of his time. Read either way, Swift's genius as a writer of English cannot be denied. 

A giant of English Theater was George Bernard Shaw(1856 - 1950) . Born in Dublin, Shaw moved to England with his family when he was 20 and stayed there for most of the rest of his long life. His early fiction writing was so poor that he could not find a publisher. Only when he began to work as a playwright did his fortunes improve. Among the many, many plays for which Shaw is famous, perhaps his most lasting (though not his most critically acclaimed) is Pygmalion (1916), the story of a language teacher who attempts to "civilize" a young prostitute by training her to speak correctly. If this story sounds familiar, it should: Pygmalion was later filmed winning on Oscar for Shaw and later again transformed into the highly popular Broadway musical My Fair Lady (1956). A good story never dies: the original Pygmalion has since been updated in the hit movie Pretty woman (1990) starring Richard Gere and Julia Roberts. As with Shakespeare, many of Shaw's plays are continually restaged or rewritten into new media because Shaw wrote on many themes which touch on the human condition, independent of time and space. 

Among the constellation of Irish talents, perhaps Swift and Shaw are two among the more brilliant stars, but much more could be written of those mentioned above and many others. Though English literature written by the British suffices as an eternal and shining canon of literature, it would be nonetheless dimmer without the considerable talents of its Irish contributors.


** lesson 9 Why Is Basketball So Popular?

Soccer and baseball have more fans, but no other sport has increased in popularity so quickly over the past 30 years than has basketball. What accounts for the sudden meteoric rise in a sport which, after all, is played best to people who are unusually tall? The secret to basketball's success lies in three particular sources: the celebrities in the game; commercial sponsorship of those players and the game itself; and the mushrooming of crowded, urban environments around the world. 

All sports have their heroes. Currently, baseball has Mark McGuire and Sammy Sosa, the home run-hitting kings. Tennis has Martina Hingus and Pete Sampras, the darlings of the courts. Soccer has players so popular that they are mobbed by fans wherever they appear, especially in Europe and South America. Only basketball, however, has celebrities who have caught the attention of the world like no others. Michael Jordan is so popular even after having officially retired from the game that there is talk of his running for public office in the United States. Dennis Rodman, the muscular, tattooed and much ballyhooed player formerly of the Chicago Bulls, makes headlines whenever he pulls another of his crazy but fun-loving publicity stunts. Former players like Larry Byrd and Magic Johnson continue to command respect for their personal integrity and unparalleled sportsmanship. Basketball shoes, T-shirts and even movies are made with these basketball superstar icons. No other sport figures can compete with their popular recognition and appeal. 

Is this international superstar status solely due to these men's talents and contributions? In no small part, of course, it is, but other leading athletes with equally commendable skills or who have performed attention-grabbing antics rarely reach the stratospheric level of stardom that basketball players enjoy. This special privilege is due to a concerted effort by the players behind the basketball players, that is the basketball leagues' owners and sponsors. 

Basketball has always been a distant third in sports rankings in the United States behind baseball and American football. Basketball league owners and managers wanted to change this traditional perception of the immutability of these statistics and in the 1960s began a concerted effort to make basketball the game of choice by hand-picking more colorful as well as professional players and by making alliances with the commercial sponsors of athletic equipment. By the 1970s, basketball team recognition in the U.S. had soared, with dedicated fans in the millions . Teams like the Los Angeles Lakers , the Chicago Bulls and the Boston Celtics had become household names. Players like Magic Johnson and Michael Jordan were worth millions of dollars in commercial advertising spots for athletic equipment manufacturers, a trend which continues to this day. Today, basketball is a billion-dollar business. 

No amount of advertising, however, can account for the number of fans who not only double as spectators but as players themselves. Basketball courts, whether in schools, parks or abandoned city lots, have sprouted throughout the urban landscape. A child is never far from a basketball ball and hoop. With land becoming more expensive in ever more crowded cities, city governments are far more likely to construct basketball courts than baseball diamonds or soccer fields. As basketball equipment is minimal and inexpensive, it is no wonder that the game has become more and more popular around the world . 

What young boy doesn't dream of becoming as tall as a basketball player, or at least of having as much money or fame? Basketball's quick pace and dynamic plays are in contrast to the much slower moves in baseball or even in much of soccer and American football. This dynamism is part of the pulse of our times, and so long as we live in a fast-changing world, basketball and its players will continue to appeal to sports lovers around the world.


** Lesson 10 Marlena Smalls and The Gullah: The Revival of a Unique Community

Does the name Marlena Smalls ring a bell? Probably not. At least not yet. If this large woman with an even larger smile and sparkling eyes has her way, however, the language, customs, and songs of the Gullah will become happily familiar to millions of people outside of the Sea Islands. For it is Mrs. Smalls' dream that through her and her performing troupe's efforts their Gullah community will no longer be an isolated, anachronistic hangover from the days of slavery in the United States, but a vibrant cultural addition to the 21st century global village.

The Sea Islands comprise a group of islands just off the southeast US Atlantic coast of South Carolina and Georgia. Descendants of slaves settled here tilling the fertile land of these islands and the adjacent coastline. A rich overlay of a mixture of West African languages onto 17th and 18th century colonial English has resulted in Gullah, a creole language featuring its unique blend of African tongues and pidgin English. Thousands of distinct African words coming from various West African languages have been identified by linguists. A few words have been added into contemporary mainstream American English. These include goober(peanut), gumbo(okra), and voodoo(witchcraft). The word Gullah itself also hails from West Africa. Many of this ethnic group's given names are taken directly from languages passed down for hundreds of years, such Abiona and Pitipa. American English is the language used when dealing with outsiders, but Gullah is the language of the marketplace and the home.

As with most African cultures, the Gullah have a rich tradition of music. The banjo, a stringed musical instrument, was an African invention brought over with the slaves to the New World. It has been popularized in both North America and Europe over the past 200 years. A great variety of drums, too, accompanied African music to the colonies in North and South America. Singing both solo and a cappella with rich harmonies was also part of the slave heritage. Despite their demanding and depressing lives, the slaves held their original languages and music as well as their masters' Christianity close to their hearts. Much of the music today involves church music, also referred to as spirituals or gospel music.

An evening with Marlena Smalls and her Hallelujah Singers is nothing short of inspirational. They are dressed at times in traditional African clothing, and at other times in the simple and conservative rural dress of Southern US society. This unusual performance includes much singing, frequent samples of Gullah as used in the marketplace or between women gossiping. A great deal of emphatic body language, and even occasional tribal dance steps to thumping drums and enthusiastic shouting are also features of the performance. Mrs. Smalls introduces the background to individual songs or other performances to help the audience - often peppered with overseas tourists - have a clearer idea of how the Gullah communicate to each other. Even without the helpful introductions, however, music lovers will appreciate the peerless singing quality of the Hallelujah Singers as they render their traditional folk songs with obvious love and pride. Interspersed with Mrs. Smalls witty and classy narrative, the evening passes all too quickly.

It is refreshing to know that some ethnic groups are proudly clinging to their priceless legacies. Despite the tragedy of their origins in slavery, the Gullah have survived and revived to produce a viable, enviable folk culture even amidst the technological wonders of the 21st century. We can be thankful that in concert or on recorded media, Marlena Smalls and the Hallelujah Singers will touch all of us listeners with their heartfelt oral tradition through the magic of music.


** Lesson 11 English in the Caribbean

When we hear the word English, we naturally think of the language spoken by those living in the United Kingdom or of the people living in England. We also often think of their language as the international language, the one spoken as a native language in Ireland, the United States, Canada, Australia, and New Zealand, countries which have had a close association with England for centuries. However, English is spoken as a native or second language in a large number of other countries which were once colonies of the British Empire.

Latin America, including Mexico, Central America, the Caribbean, and South America, is often thought of as a linguistically homogeneous area of Latinate languages (those languages like French, Italian, Portuguese, and Spanish which originated from Latin). This is generally true, as the vast majority of people there speak Spanish or Portuguese as their mother tongue. However, a number of small Caribbean island nations were also once part of the British Empire, accordingly, their citizens even after independence speak English. These nations include Antigua and Barbuda, the Bahamas, Dominica, Grenada, Jamaica, Bardados, and the Republic of Trinidad and Tobago.

Do the Caribbean English speakers speak British English? Not exactly. All over the world where English has been spoken for hundreds of years by speakers of other language, certain special accents or dialects have arisen. India is famous for "Indian English", "Irish English" is unmistakable, too. Likewise, Caribbean English has its own special patterns, vocabulary, and even grammatical forms different from the standard RP (received pronunciation, also referred to as Received Standard) of British English. These special features include a lilt or "sing-song" sound to the language, and plenty of local slang.

As only a relatively few people live on these islands, how can we hear their special dialect or accent? One kind of pop music called reggae is the easiest way outside of befriending someone from these nations. Reggae music has been popular since the 1980s, when performers like Bob Marley of Jamaica pleasantly surprised the world with their own original reggae music as well as their interpretations of other well-known pop Anglo music. Reggae is famous for its strong, often syncopated beat, laid-back singing style, and, of course, the "island" dialect. Another perennial music favorite is calypso, which is also sung in the Caribbean island English dialect. The hit song "Yes, We Have No Bananas", is reminiscent of this drum-heavy musical style, especially from Trinidad and Tobago.

Given the islands' historic ties to both the United Kingdom and the United States, it is little wonder that today the people of these small nations continue to use English in government, academic, business, and trade. Local language still exist alongside the Caribbean English dialect, too, but they are mostly the patois of the marketplace and home. Many of the residents of this area, also referred to as the West Indies or the Antilles, have emigrated to the UK or the US and, because of their linguistic prowess, have done relatively well as so-called "third world" immigrants. A few writers of contemporary renown also hail from this area, as do some sports figures.

If you plan to visit any of the above-mentioned islands for any purpose, do not worry about your language skills. Caribbean people are well-known for their friendly, patient dispositions. After a few days, your ear will become attuned to the lilting cadence of the lovely Caribbean English dialects, and your stay in this tropical paradise will be all the more rewarding.


** Lesson 12 The Louvre: The World's Best Museum?

Paris, City of Light, and of art. A playland for lovers and a painter's dream. What better place to situate the Louvre, considered by many to be the world's best museum of art? what makes this museum so worthy of that honor? 

The museum building, or, more properly, the complex of buildings themselves is a good place to start. As with most Western and a few Asian and South American museums, large palaces or other traditional architecture are used to house museums of art and of natural science. In the case of the Louvre, officially known as Palais du Louvre (The Palace of the Louvre), the main building used today was formerly the fortress of King Philip Augustus in the 12th Century. Not until 1546 did King Francis I begin to redesign and add onto the fortress. Subsequent kings did the same, especially during the 17th century with major additions by Louis XIII and Louis XIV. Not only did these kings and their ministers add to the buildings, they also stocked within their rooms the finest art that money could buy. After the French Revolution, the Palais du Louvre was opened to the public. In the early 19th century, both Napoleon and Napoleon III added to both the structures and the collections. A controversial see-through glass pyramid-shaped structure was added by the architect I. M. Pei in the 1980s. As a consequence of centuries of continuous construction and the amassing of art treasures, today the Louvre offers a world-class collection of both French and foreign art. 

The outer shell of a museum, however, no matter how artistic or historic, cannot alone make a museum truly great. The inner collections are of course of paramount interest to both the art researcher and art lover alike. The Louvre does not disappoint them. Three of the West's premier works of art are here: the statues Victory of Samothrace and Venus de Milo accompany Leonardo da Vinci's most famous painting, the Mona Lisa. These alone attract art devotees from around the world, but for more awaits them. The French painting collection is, not surprisingly, unsurpassed. Other major painting collections include works from the middle ages and Renaissance. The treasures of the French royalty are on display here, too, such as their bronzes, miniatures, pottery, tapestries, jewelry, and furniture. Greek, Roman, Egyptian, and Mesopotamian antiquities as well as early Christian artifacts are also considered important collections. This clearly is not a museum to be seen in one morning!

Finally, the site of the museum complex contributes to the mystique of the Louvre. Paris has long been considered one of the world's most charming cities, with its endless winding streets amidst spectacular royal and religious architecture. The fortress built by King Philip Augustus was situated on the right bank of the Seine, overlooking - at that time - splendid bucolic scenery. Today this prime location is within walking distance of many major Parisian tourist attractions, like the Cathedral of Notre Dame, the Royal Palace, and the National Library. One could easily spend a whole week touring the heart of Paris centered around the Louvre. 

Taken altogether, then, the Louvre holds its own as one of the best museums - If not the best - among the dozens of major and internationally famous art museums around the world. Its many and varied buildings, the unparalleled collection of prestigious works of art, and the delightful site of the grounds overlooking France's most famous river all contribute to make the Palais du Louvre a must-see attraction for the serious art connoisseur and art museum-goes alike. Meet you at the Louvre!


** Lesson 13 The Ivy League Schools: Excellence in Education.

The first permanent English settlement in the New World was at Plymouth Bay in what is now the state of Massachusetts in 1620. Merely 16 years later, a group of successful settlers in New Town (renamed Cambridge after their alma mater) started a college. They named it after the Puritan minister who willed half his estate and all his books to the college. This clergyman's name was John Harvard, and his namesake remains the most prestigious among the more than 2000 institutes of higher education in the United States today.

Harvard is not the only great school in the US, of course. A small industry has grown up around the ranking of the best tertiary schools, and year after year, seven schools dominate most of these Top Twenty or Top Fifty lists. Harvard is nearly always at or close to the top, joined frequently by Yale (in Connecticut), Princeton (in New Jersey), Dartmouth (in New Hampshire), Cornell (in New York state), Columbia (in New York city), the University of Pennsylvania, and Brown (in Rhode Island). These eight private universities are collectively referred to as the Ivy League schools.

Why the name? Ivy is a vine; that is, a plant which grows up or along the surface of other plants such as trees, or, in the human landscape, along the sides of stone buildings. As these eight universities are old (the youngest among them, Cornell, was founded in 1853), ivy has had plenty of time to decorate the outsides of the more historic buildings on these campuses. The word league, however, is more an invention of imagination than a reality. Though there is an association called the Ivy League, it refers to the above schools' participation in an American football athletic conference rather than to any academic alliance. Further, despite the lengthy academic lineage of these schools, the footballing Ivy League was not formally formed until 1956, though highly competitive football and other athletic games have been hotly contested among the schools for many generations.

Since these institutes of higher learning had such an early start in the history of the United States, it is not surprising that they should individually and collectively have exerted a great influence on American society. Their status within national scholarly circles is unparalleled. Admission to these universities is highly demanding: for every student lucky enough to be accepted, many are rejected. As these universities are private, they are relatively expensive. Offsetting the extremely high tuition are many opportunities for scholarships. These scholarships are awarded to meritorious students regardless of their backgrounds.

Additionally, the roster of the faculties of these schools reads like a Who's Who list of important Americans (and quite a few foreigners, as well). Their intellectual integrity shows in the number of Nobel and other major prizes awarded which they have garnered over the years. Some of the country's most famous doctors, statesmen, engineers, scientists, and educationists have studied and taught within these ivy-covered walls. No fewer than 14 US presidents have earned degrees here, including six at Harvard, six at Yale, and two at Princeton.

Though only a select few can join the ranks as Ivy Leaguers each year, Americans are endowed with a world-class tertiary educational system second to none. Not every graduate from an Ivy League school "makes the grade" in life; even a first-rate education is no guarantee of success. Still, those who do enter and leave the Ivy League universities in the northeastern United States have a much better than average chance to join the ranks of the movers and shakers of not only the US society, but, once back in their home countries, of their native lands as well.


** Lesson 14 Alpine Treasures

From the Atlantic Ocean to the Ural Mountains stretches the continent of Europe. The most striking geographic feature within this densely-populated area is the Alps Mountain Range, commonly called the Alps, The Alps covers most of Austria and Switzerland as well as significant areas of Germany, France, and Italy. The picture-perfect land and lifestyle of the Alps contain many treasures for all the peoples of the world. Who hasn't dreamed of visiting the Alps for a vacation? If you are lucky enough to vacation in the Alps, what delights await you?

The ladies can look forward to dirndls and Alpine flowers. A dirndl is a special Alpine dress worn particularly by the German-speaking populations of the Alps (in most of the Swiss and all of the German and Austrian areas). This long, often colorful and simple-patterned dress includes a full skirt, gathered waist, and tightfitting bodice. Most women fall in love with a dirndl the moment they see one. Save up to buy one, though. Most dirndls are hand-made and rather pricey. Compared to the cost of the intercontinental voyage to the Alps, though, a dirndl is well worth the expense. The wearer will have a cool weather treasure to wear for many years.

If dirndls are really too expensive, though, the hundreds of species of Alpine flowers will also delight not only women, but all nature lovers, for free. Of course, to see these botanical wonders, one must visit the Alps during its relatively brief spring through fall, that is, between June and September for most blossoms. The hills are alive with tiny, multi-colored petals in sometimes bizarre shapes. Don't touch! Most plant species are protected by laws carrying stiff fines, even for unsuspecting tourists. Instead, these natural treasures are available on the many postcards or in the coffee table books available at the ubiquitous souvenir shops and bookstores throughout the region. Taking one's own pictures or movies is an even better idea. With luck, it is still possible to find the rare edelweiss growing on a mountain slope. Its yellow center with white star-like petals has become an Alpine symbol, present in many folk art handicrafts.

Speaking of handicrafts, in addition to the dirndl, there are other assorted wares which can be taken home as a fond remembrance of one's all-too-brief stay in this mountainous playground. Alpine women take pride in their embroidery. Scarves, shirts, blouses, wall hangings, and table coverings can still be bought in the smaller, more remote hamlets in tiny mountain valleys. Many modern imitations are also available, however, so be sure of any item's authenticity before buying. In the off-season from farming, some Alpine men enjoy woodcarving. Items from as large as grandfather (also called "cuckoo") clocks to palm-sized miniature animals, farm utensils or equipment, or creations from the imagination can be had at roadside stands or local markets.

It's a pity that so much local food does not carry well; otherwise, Alpine dairy products, sausages, and breads are well worth taking home. On the other hand, bottled wild honey with its extra-thick consistency and exotic wildflower tastes and scents is relatively easy to transport with care in one's carry-on baggage. Mountain wine and liquor may also be carefully taken home. In the meantime, enjoy the calorie-laden but delicious Alpine cuisine where it was meant to be eaten.

Some Alpine treasures cannot be taken home. World-class skiing, mountain climbing, mountain hiking, and white-water rafting are among them. The views of the permanent glaciers of Mount Blanc, the Alps's highest peak at just over 4,700 meters will last a lifetime. Jolly Alpine music and dancing quicken the heart and set the feet tapping. With so much to see and appreciate, perhaps the next priority vacation spot on the discriminating traveler's list should be the Alps.


** Lesson 15 Webcams: Electronics tool or the end of privacy?

What are webcams? The word webcam is a compound word formed from two abbreviations, "web" from the World Wide Web and "cam" from camera. Webcams are cameras which are situated at various places and linked to the World Wide Web. They allow 24-hour viewing of a wide array of places and activities around the world. They can be as educational as they are fascinating, entertaining as they are eye-opening. Not everyone raves about this new technology, however. Some cite sinister implications in a technology which can unobtrusively spy on our goings-on without our permission. Others note that with rapid increases in telephotography and the science of acoustics, the days of privacy are numbered. Anyone can mount a webcam with a telephoto lens and microphone, aim it at his neighbors’ living room or bedroom, and then broadcast one’s "private" life to the whole world. A script for the next sci-fi film, or a current reality? Are these doomsayers overreacting, or is their charge legitimate? 

On one side of the debate are those who point out that webcams offer more real advantages than supposed disadvantages. They cite numerous websites on which people can observe the world around them for educational or aesthetic purposes. Today one can watch urban scenes like city streets and squares or even haunted houses! Nature lovers can revel in the undetectable webcasting of bats, sharks, and penguins at various sites around the world. A huge collection of webcams can be found at www.earthcam.com. Another great collection can viewed at www.discovery.com. Most educators, parents, and politicians would agree that these websites allow for a better understanding of both the human and natural environments in the world we all live in. Certainly, they would say, webcams provide an invaluable service and should not be restricted. 

Others are not so sure. every technology cuts both ways. Even fire can cook food as it can burn our flesh. Railroads gave us faster and more convenient transportation as they simultaneously signaled the death knell of many species of migratory animals as well as served up noise and air pollution. Nuclear energy gives millions heat, light, and power just as it creates unwanted radioactive side effects. Seemingly harmless technologies such as telecommunications also have their dark side. 

Opponents of webcams note that the sleazy, commercial instinct of some people is unleashed with the offering of for-pay viewing of certain starlets or other celebrities’ home lives, which most people prefer to think of as their "private" life. Perhaps not much longer. In some controversial cases, webcams have been mounted in public installations such as washrooms so that voyeurs may watch the intimate goings-on of anonymous people. Even more sinister in the capacity for the new technology to be used in both economic espionage and "good old" state-to-state spying. Webcams mounted surreptitiously in business offices or factories can reveal on-screen "secrets" from those unaware that they are being bugged. With microelectronics technology reducing the size of telecommunications devices, this is no paranoid fantasy any longer. 

The human mind is as devious as the many progressive devices it produces. No matter what technology mankind develops in the future, we must move forward and allow these new technologies. Only by practicing them - for good or bad - can we realize our human potential. On balance, too, despite the horrific deadly or sinister potential in technology, the world offers a more productive, comfortable, and progressive environment today than in our previous low-tech centuries. At the end of the day, it is not our technology that we must learn to control so much as ourselves.


** Lesson 16 When is the best time?

Some people go so far as to say that time does not really exist; it is all in the mind, they claim. Others note that according to astrophysicists, time really does exist; it is inseparable from space, coexisting in what these scientists call the "time-space continuum." No matter which view you may hold, time is of relative importance in different cultures. However, when traveling, doing business, or studying in a German-or English-speaking country, it is a good idea to consider time to be of the utmost importance.

Many people have noted that the Germans and English are both methodical and well-organized. Naturally, not everyone among them is, but these peoples do seem to share a penchant for orderliness and punctuality. Clocks and time have played a great part in defining the character of the Anglo-Saxons. The geographic use of time began during the British Empire with the world divided by latitude and longitude, with zero degrees longitude running through the observatory at Greenwich, in London. According to the British of that day, the world began its time-keeping from London - and it still does. Time is of paramount importance to these Europeans and their overseas descendants. If you are visiting or staying in these countries, here are a few pieces of advice to help you make the transition to a time-centered civilization.

As you probably already know, being punctual - to the minute - is held in high esteem among them. Time is the most valuable commodity one can have, according to the doctrine of the time worshippers. We are not given very much of it whilst on this planet, and we should do our best to utilize it efficiently each and every day, they say. Wasting others' time by forcing them to wait is a sign of disorganized living, a sort of admission to being low-class. It is also seen as an insult to those kept waiting, as if to say, "Your time is not that important." To them, this attitude borders on sin itself! In business, being late even only a few times may make the difference between your getting a promotion and being kept "in your place." For social dates, it is a sign of slovenliness at best, rejection of those waiting at worst. In school, never burst open the door of the lecture hall to announce, "I'm sorry I'm late, sir" as is the custom in many countries. The double crime of being tardy and interrupting the proceedings which began on time occurs, with a likely prejudiced and unfavorable grade awaiting the hapless student.

Of course, being late can sometimes not be avoided, as in unexpected traffic jams, home emergencies, or having been given the wrong information of date or place. When these all-too-human mishaps do occur, it is important to explain the reason for being late. It is also a good idea, of course, to apologize for the useless waiting and to assure the other or others that it will never happen again. In this age of cell phones, every effort should be made to call ahead if tardiness of more than ten minutes is unavoidable, especially for business or professional appointments or important dates. The last phrase anyone wants to hear is a frosty "You could have called." That is the prelude to a ruined evening.

Not everything begins exactly on time, even in Anglo-Saxon culture. Many casual parties are "open" there. The same is generally true of backyard barbecues and picnics. Dinner parties, on the other hand, are obviously planned around a meal time; one should make every effort to arrive on (not before) time. A friendly "Drop by this evening" invites common sense to interpret: too early during the evening may embarrass the host who is eating dinner, while too late may disturb those who prefer going to bed early. A call first to make sure is never out of line.

Remember that time is relative in importance to people within a culture just as it is between cultures. Nothing is more important than human relations. If you commit the "crime" of being late with Anglo-Germanic friends, simply apologize. Few people intentionally keep others waiting, after all. Remember, too, that, "When in Rome, do as the Romans do." In English-and German-speaking lands, this means "Time waits for no man!"


** Lesson 17 Precious and Semi-precious Stones

"My! What a beautiful ring you're wearing!" This compliment never fails to flatter and honor the lucky wearer of the ring or other pieces of jewelry bedecked with precious or semi-precious stones. Most people know the names of only some of these natural treasures. Many people are surprised to learn that all semi-precious stones can be bought inexpensively, not to mention that the precious stones can also be had for far less than one imagined. However, as with everything else in life, you have to pay for the best quality. This lesson will give the reader both information and tips on gem stones and their purchase.

Just what are precious and semi-precious stones? The word semi refers to anything which is half or only partial; thus, semi-precious stones are not precious, by definition. Actually, some high-quality semi-precious stones are far more expensive than some low-grade precious stones, so the terms "precious" and "semi-precious" when applied to stones do not refer necessarily to their cost.

All authorities on gems agree that the diamond, ruby, sapphire, and emerald are precious stones. Some of these experts include the opal as a fifth precious stone while others consider the pearl in this class. The latter may surprise the reader, but on reflection, pearl are also a kind of stone, though organically produced by certain shellfish rather than by geologic forces.

Semi-precious stones include all other stones considered worthy of use in jewelry. The list of these stones is very long; suffice it to say that there are several hundred such stones, though most people are aware of only a couple of dozen of their names, and few people can readily recognize more than a couple of any type of stone at all.

Diamonds and the colored stones ruby, sapphire, and emerald are often considered the most expensive among all stones. This is generally true, though quality is more important than stone type on price. One can buy a "real sapphire" for US$10, but it would be considered not much better than junk to a jeweler. These professionals consider several features of stones before assessing their value. Carat size, or the weight of the stone (one carat = 200 milligrams) is one such feature. The cut of the stone is another. Some styles of cuts are considered more costly than others; besides, in the technical cutting of the gem from the rough stone, great care must be taken not to cut into or scratch the surface of the finished stone. The color is also important. Rubies, sapphires, and emeralds, for instance, in order to fetch the highest prices, must be solid colored throughout. Finally, clarity or translucence, with neither streaking nor a "cloudy" inner appearance, also determines the final price. Gems with these qualities are far and few between, commanding nearly astronomical prices. A good jeweler will advise you of these characteristics and how to look for and evaluate them yourself. Also remember that for a gem ring or pendant, roughly 70% of the value of the piece of jewelry is in the primary stone(s), with the rest in labor and metal.

Specific names of semi-precious stones are too numerous to mention, but jade is well known to Chinese. The finest jade (apple green in color) commands very high bids at auction. The trouble with semi-precious stones is that they are not so hard as precious stones so they far more easily scratch, crack, or chip. If this happens, the value of the semi-precious stones plummets. Diamonds, the hardest natural stone, and rubies and sapphires, the second hardest, are actually rather hard to deface.

Don't let anyone sell you a "good deal on a gem" on the street. Go to several professional jewelers before committing yourself - and your money - to a piece of jewelry with precious or semi-precious stones. Part of the value of that good piece of jewelry is the fact that it can be handed down generation after generation with increasing value. People in all cultures never seem to tire of the brilliance of gems.


** Lesson 18 Hot Animals Around the World: The Koala

Why are all those people standing in line in the hot sun at the zoo? Maybe the zoo just opened a koala exhibit. With the survival rate of native Australian koalas on the rise, more and more zoos around the world are adding a "koala house" or "koala exhibit" to their roster of special animals. And the people keep coming, whether merely to catch a glimpse of one or, if really lucky at zoos which permit it, to hold and be photographed with one.

Why are koalas among the most beloved of all animals? At times referred to as "koala bear", this Australian marsupial is not a bear at all. It is one of the few tailless mammals beside the apes and man. Yet apes are not often considered cuddly; indeed, they are often feared for being either too large or too naughty. This Australian real-life teddy bear, instead, is the best of all worlds: it is quiet, soft, neither too large nor too small (adults are usually 65 to 80 cm. long), and really cuddly! With its soft fur, leathery nose, rounded ears, and big eyes, most people seem to melt when near one. Its disposition is perfect for children and adults alike; it rarely makes a fuss, even when being held. (Try that with a baby tiger!) No wonder the lines to see, hold, or just touch the koalas are always among the longest at zoos.

One reason zoos today are able to keep koalas is the rise in the koala population in its native habitat, the eucalyptus forests of southeastern Australia. This nation, famous for its unique fauna and flora, is now allowing applications for the professional export of its protected species to overseas zoological gardens. Once hunted for its fur, this arboreal leaf-eater is today protected by stringent laws and is making a slow but steady comeback. Indeed, everything about the koala seems slow. It sleeps more than 12 hours a day (often much more), eats only choice leaves from eucalyptus trees (which can now be grown in many zoos to provide the more than one kilogram of leaves that each adult koala needs per day), and rarely if at all descends to the ground because it is such a slow runner (from wild Australian dogs called dingoes or from human hunters). As koalas are such a great draw for visitors, many zoos are trying to include them among their species.

Mother koalas give birth to babies only every other year. These young ones, as with other marsupials, spend a period of time inside the mother's "pouch" before venturing out into the world. In the case of the koala, this pouch is located below and in back of the mother; the small koalas can climb out directly from the pouch and onto the mothers back before learning to feed and fend for themselves. With all other marsupials, the pouch is located in the front, perhaps most famously with the kangaroo, where the "joey" can sometimes be seen popping its head out of its soft, warm pouch to survey the world about it safely.

Until the 1980s, zoologists feared that the koala might go the way of some other rare marsupials. Just as their eucalyptus habitat was being destroyed to make room for the ever-increasing suburban Australians, diseases peculiar to koalas began to take their toll. Combined with weak or non-existent laws against the hunting or poaching of this national treasure, the koala seemed doomed to extinction. Today, the koala has climbed back from the brink of extinction and is thriving again. Its main enemy today is forest fires. This slow-moving mammal cannot move quickly enough to escape the deadly fires which perennially ravage the land. With more land being set aside to protect this and other Australian species, however, the future of much of this special land's animal wealth seems secure.

All animals deserve man's protection, but some animals seem to attract the attention they need. The koala, one of the symbols of the great Down Under, is one of these. Holding a koala is fun, educational, and inspiring. If Australians could cooperate to save this special species, mankind should be able to prevent the extinction of all other animals, too.


** Lesson 19 Asian Americans

In the last census conducted by the U.S. government in 1990, one fact caught many people by surprise: the percentage of Asian Americans had grown faster than any other segment of the population. European Americans had, as expected, continued their slow decline in percentage of the total U.S. population, though they were still dominant at about 76%. Black Americans had stabilized at about 12% of the population. Hispanics had continued their fast growth and were, at 9%, aimed at toppling Black Americans as the country's largest minority group. The growth in Asian Americans, however, surged from only 2% of the total U.S. population in the 1980 census to 3% in 1990. By the year 2000 at least 4% of Americans will be of Asian ancestry.

This relatively huge increase has caught many demographers by surprise. Clearly a new force is developing in US demography, but few people seem to appreciate its implications. The Asian Americans are here and are here to stay, but exactly who are they, and what does their rapid increase mean for the country as a whole?

As a multi-ethnic nation, it should not be surprising that Asian Americans are becoming an increasingly large and important sector of the "rainbow nation" some Americans prefer to think of their country as. Indeed, the only surprise about this segment growing so fast is why it has not occurred sooner. After all, Asia is home to 60% of all the people in the world. However, Asia is also a vast land, encompassing East, Southeast, South, and West Asia, each region significantly different from its neighbors. Further, there is no sense of unity within Asia, as there is, say, among European or Latin American countries. Indeed, the term "Asian Americans" is more a fiction of the European mind, since people from this area unfailingly refer to themselves as Chinese, Japanese, Filipino, etc, rather than as Asian-Americans.

For more than 100 years, three primary groups of Asians emigrated to the United States: Japanese, Chinese, and Filipino. However, since the end of the Vietnam War, other groups from Asia have become increasingly prominent, especially those from Vietnam, Korea, and India. In addition, Iranians and Israelis from Southwestern Asia have also entered the U.S. in large numbers.

The patterns of Asian immigration have changed greatly over the past 30 years. In 1970, 96% of Asian Americans were Chinese, Japanese, or Filipino; as of 1997, this percentage had dropped to 55%! In that year, 24% of Asian Americans claimed Chinese ancestry, 21% Filipino, and 10% Japanese. The "newcomers" among Asian Americans include the Indians at 13%, Vietnamese at 11%, and Koreans also at 11%.

What real numbers are we talking about? There were estimated to be nearly 9,600,000 Asian Americans in the U.S. in 1997. With such a high growth rate, there will be more than 10 million of them this year and perhaps 32 million in 2050 (about 8% of the total US population at that time). Where do Asian Americans live? Currently, an astounding 40% of this regional group lives in California. Other states with relatively large Asian American populations include New York, Hawaii, Texas, New Jersey, Washington (the state), and Illinois (which contains Chicago). Overall, the West is home to 54% of all Asian Americans, the Northeast 19%, the South 16%, and the Midwest 11%.

What about future trends? As Asian nations continue to prosper, it is likely that they will contribute more to US immigration, especially from Southeast Asia and India. All of these groups continue to have above-average birth rates. On the other hand, Chinese and Japanese Americans have very low birth rates; consequently, the percentage of these ethnic groups among the total will continue to fall. All in all, America can look forward to an increasingly large number of Asians enriching their new home with their diligence, investment, and diverse cultural contributions.


** Lesson 20 Scourge of the Plains: Tornadoes

Ellen Mae stepped out of her two-story home in central Illinois. "Fine morning," she said to herself after checking the weather, and then went back inside. The radio had mentioned a severe storm advisory, but the sky was clear, and it was rather calm. Still, she decided to be safe and kept her radio on.

About noon she felt a strange kind of pressure. Looking out her window, she noticed the sky had become overcast. Low, rounded, oddly colored clouds were forming. It was still and oppressive. "Maybe I'd better listen to the weather report again," she murmured to herself.

Again the radio forecast severe weather, warning citizens to listen for the siren and seek shelter should a twister, scourge of the plains, come down from the heavens like a "Devil's tail." "I doubt it'll happen over Crossville," she comforted herself. "It always happens in other towns."

By two o'clock it started to rain, and the wind picked up, too. The apple tree in front of Ellen Mae's house started to pitch back and forth violently. Her dogs started to bark and howl, and that was when she heard that awful sound.

At first she thought it was a locomotive, but she quickly remembered that there was no railroad within 20 miles of her home. She looked into the sky and then noticed it, a dark, swirling mass of black cloud sucking up everything it touched and hurling objects at horrific speeds straight up or straight to the side. Ellen Mae ran as fast as she could down into her storm cellar, a special room which had been prepared by her father when he was still alive. This room was located in the southwestern corner of the basement and had a door with a strong bolt. Ellen Mae ran in, locked the door behind her, and waited.

She didn't have long to wait. With shrieking and swooshing sounds right out of hell, the funnel cloud passed directly over her house. An enormous vacuum cleaner, the twister blew the house apart, scattering five generations of Ellen Mae's family belongings over half the rural country she lived in. Within minutes, the winds had stopped, and an eerie silence replaced the cacophony of moments earlier. Feeling it was now safe to venture out, Ellen Mae unbolted the door, peered out, and started to cry. She could look straight up into the sky. Even though she had lost her house and everything in it, she felt lucky. She knew that every year, hundreds of people could perish in tornadoes.

Just what are these "devil storms"? They go by many names across the great Plains of the United States and Canada, not to mention many other countries around the world, but tornadoes are perennial plagues in central North America. The conditions there - flat land and proximity to cold air masses (from the Rocky Mountains to the west) and warm and humid air masses (from the Gulf of Mexico to the south) provide the optimum breeding ground for tornadoes. According to the US National Weather Service, tornadoes form from thunderclouds and can reach swirling speeds in excess of 600 kilometers per hour. They last from minutes to an hour or more and can blast their way across as much as 150 kilometers of terrain at about 50 kilometers per hour. They vary in width from a few meters to 1500 meters (average 200 meters). And they strike fear into the hearts of everyone.

The safest place to be when a tornado is in one's area is a basement, preferably the southwest corner (where the tornado normally comes from). If driving, track due north or south, as tornadoes usually move from west to east. Weather prediction and tracking these days is far superior to earlier years, but tornadoes can appear without any warning at all, as a large one did right in the heart of Salt Lake City in 1999, leaving a trail of shocked, wounded, and dead as well as pulverized property.

Though relatively few people have ever seen a tornado, those who have wish they hadn't. The "Finger of God" is nature's atmospheric fury at its worst.


** Lesson 21 What's So Big about Moby Dick?

A pretty, young lady goes swimming alone off the coast of New England in twilight. She is an agile swimmer, full of grace and speed. Without warning, though, she disappears from sight, only to reappear a moment later, screaming in pain. A few shocking moments later, she is again dragged under the water, this time only to reappear the next morning in pieces of the shore.

Sound familiar? By now nearly everyone has seen or heard the story of a killer Great White Shark in Jaws, a hit novel turned into a blockbuster movie. Few people realize, however, that the story broadly follows the events depicted in what many people consider one of the best of American novels. Published in 1851, Moby Dick has been making waves ever since.

The author, Herman Melville, was born in New York on August 1, 1819. As a youth in a large family he suffered many insecurities due to the family's constantly changing fortunes. As a young man he worked as a farmer and seaman, the latter providing most of the material for several of his later novels and essays. In his 20s Melville found fame with two novels based on imaginary happenings in the South Pacific. Moby Dick, ironically, was not well received. Afterwards, Melville produced another masterpiece, Billy Budd. He continued writing until his death in 1891.

Why has Moby Dick since become such a classic despite its initial lukewarm reception? Melville had a keen eye for not only the human condition but for the tenor of his times: the Unites States was in his day a country of disadvantaged and mistreated immigrants (many of whom became sailors and laborers), with untrammeled capitalism crushing both nature and man underneath its new country exuberance. His stress on the individual and fate - often pessimistically, or at least realistically - were harbingers of the future of literature.

Why does the story of Moby Dick continue to enthrall generation after generation? The story line is simple enough: a mad sea captain vows revenge against a white whale which, on a previous expedition, bit off one of his legs. In his vain attempt at “justice” against nature, the captain meets the ultimate tragedy. This was no documentary, however; the characters and setting become vehicles for far larger and more universal themes of the setbacks and successes of the human spirit as well as its darker urges. So accurately does Melville depict the whaling scenes and sea voyages that the reader is taken on an exhilarating ride. Coupled with the absorbing, mad Captain Ahab, the book is “a good read” even by 20th century standards.

Earlier in this century, the Nobel Prize winner Ernest Hemingway penned the Old Man and the Sea, another story of a man's struggle with nature on the open ocean. This theme strikes a chord in Americans, whose culture developed along the Atlantic coast of North America and whose seaward passage from the Old World took them to the colonies of the 18th century or the young country of the 19th century by the millions. This fascination with the maritime still holds today: over half the population of the United States lives in counties touching the Atlantic, Pacific, or Gulf coasts. Perhaps some future writer will once again use the metaphor of sailors and the sea to create yet another Great American Novel.



** Lesson 22 Boston: Hearth of American Culture


When people think of “American culture and values”, they are unconsciously referring to a set of principles, a world view, and a lifestyle which can best be found in Boston, capital of the state of Massachusetts and the major city in all of New England, those six relatively small states tucked away in the northeastern corner of the United States. Although Boston is perhaps the seventh or eighth largest city in the U.S., no other city in America can compare with the influence which Boston has had on the development of government, education, medicine, and the arts.

This influence is due in no small part to Boston's central role in the building of a new nation. Many people think that the Unites States was established in 1776; however, that was the year of the Declaration of Independence, a revolutionary document claiming self-rule from its mother country, England. Actual independence - the formation of a government with an acting president (George Washington) - did not begin until 1789. Boston was nearly middle-aged then, as it had had its beginnings a century and a half earlier, in 1630. It maintained its position as the colonies' pre-eminent center for politics, education, and commerce until the mid-18th century, when both New York and Philadelphia (the young nation's first and second capitals, respectively) overtook Boston in size.

Boston was settled by religious immigrants from the Church of England. It was with these early settlers that the first outlines of an American culture began: a strict adherence to religious dicta, diligence in work, educational aspirations, and a conservative lifestyle. Because Boston is closer to Europe than any other city in the U.S., it was the point of entry to the colonies until the 19th century, when New York became the new magnet for the “poor, tired, and huddled masses” who were to become the backbone of the new American economy. Boston remained, however, an important commercial center until the 20th century.

Today Boston caters to finance and banking, education, and medicine, with some of the top international mutual fund and insurance companies, world-renowned educational institutes, and state-of-the-art medical centers and schools. The city has also managed to preserve much of its earlier identity as the home of the American Revolution; thus, tourism is an important sector in the economy of Boston as well. Like San Francisco or New Orleans, Boston has a reputation for being a pleasant city to admire while walking around it.

What can one do in Boston? Important historic sites, well-preserved examples of architecture from the 17th-20th centuries, and spacious parks invite the tourist or resident to “smell the roses” while in Boston. Its unhurried but sophisticated citizens boast not only high incomes but also high levels of education. Music flourishes here: the Boston Symphony Orchestra, the New England Conservatory of Music, and the Boston Pops Orchestra offer first-class musical entertainment in both public and private venues. The Museum of Fine Arts is a major world gallery. Science Park, situated midway between Boston and its major satellite city, Cambridge, offers the Museum of Science. Had enough of “high-brow culture”? Boston affords its citizens and visitors many first-class restaurants and shopping dockside in Faneuil Hall. Historic walking tours are a must for the tourist, especially Boston Commons, a city park, and Beacon Hill, with its roads still paved with the original stones from the 17th century. Admirers of university campuses steeped in tradition should see Harvard, the nation's oldest university (1636), as well as the Massachusetts Institute of Technology, Emerson College, Boston College, and Boston University, all in the metropolitan area.

In short, no matter one's interest is, any visitor is sure to enjoy his stay in Boston, hearth of American culture and still a leader in education, medicine, and music.


** Lesson 23 Paper's Long March

Remember when the 1980s brought us the first wave of the modern computer and electronics revolution? At that time, heady young technocrats foresaw “the paperless office.” It was claimed that paper would become a thing of the past as everyone would access all information needed from video screens.

The reality today is quite different. More paper than ever is being used in offices, schools, and residential homes. One's first possession in life is a birth certificate, made of paper. Childhood immunizations are recorded on paper and kept in the doctor's office and at home. What would school be like without paper? Paper follows most people throughout their education and into their working life. Wedding invitations and marriage certificates are printed on paper, as are virtually all major life passages and social occasions. Finally, a death certificate on paper will continue to be around long after the person named on it. Perhaps the one item which defines modern civilization more than any other is paper.

The word paper derives from papyrus, the name of a riverside plant similar to grass, from which an ancient form of paper was used in Egypt and Mesopotamia. It could be argued that these empires were made possible by the use of official records on papyrus. However, paper as we know it today has its origins in the Han Dynasty of China. In about A.D. 105, an official in the imperial court produced the forebear of what has become today the world's most indispensable product. The art of paper making reached westwards to Baghdad, Iraq in the 8th century at the height of the Islamic culture. From there it entered Europe, where it was polished into its contemporary form during the 19th century.

Paper can be made from any plant, but trees are the best source of cellulose for paper production. In fact, earlier forms of paper were made from processed cotton waste and rags, but trees contain a better proportion and type of cellulose than any other plant. In countries with a deficiency of forest land, other natural fibers such as sugar cane pulp, bamboo, cereal straws, flax, and hemp are used. Today's paper and paper product mills rely on a steady inflow of wood logs or chips. In the US alone, the paper and paper products industry in worth more than US$80 billion, with world production well over 100,000,000 tons annually.

Everyone knows what paper is, since most people use at least one sheet of it a day, but few people stop to consider the different kinds of paper available to us today. Office workers are well aware of the many kinds of paper they use, such as regular typing or computer printing or copier paper. They also come into contact with bond, a high-grade paper used for important documents. It is thicker and more durable than other forms of paper. Book paper comes in at least four different finishes. These may be seen in books, magazines, brochures, and calendars. Newsprint is used for newspapers and some magazines or books, while craft paper is used for shopping bags. Paperboard is seen daily as box lunch containers, cardboard boxes, and even building materials. Finally, sanitary paper has been developed for use in tissue paper, paper toweling, and paper napkins. Carbon paper, postcards, and envelopes are also daily use items made of paper. Even a tea bag is made of paper!

Paper and its products seem endless, but conservation of even the abundant resource of trees is in everyone's interest. Recycling of paper and better designed pulp and paper factories have helped decrease waste. Many offices encourage the use of both sides of a piece of paper, for example, and students or private organizations sometimes collect old newsprint to send to reprocessing centers. By conserving paper, the average paper user in his lifetime can save at least one tree from being felled. As valuable as trees are, and as valuable as paper is, everyone should cooperate to use this essential commodity wisely.


** Lesson 24 Coffee or tea break?

Do you prefer a coffee break or a tea break? Are you getting off the lift at the ground floor, or are you going to get off the elevator on the first floor? Travelers to English-speaking countries have to adjust to differences between British and American English. There are also cultural traditions to understand, ways of life which differ between London and New York, Auckland and Toronto, and Sydney and San Francisco. Learning these differences is fun, and, when you travel to different English-speaking countries, it's very useful.

So, what is a coffee or a tea break? Americans and Canadians prefer coffee drinking to tea drinking. Tea lovers need not worry, though; millions of North Americans drink tea and only tea every day. Though teahouses are rare there, every supermarket has a wide variety of Far Eastern, South Asian, and herbal teas to choose from. Still, coffee is the preferred drink in the Americas; after all, South America is one of the world's greatest coffee-producing areas. One social custom in the U.S. and Canada is the mid-morning and mid-afternoon coffee break. This is very informal; it may be spontaneous (Hey! Let's break for coffee) or institutionalized (The coffee break in our office is from 3:30-3:50 daily). Coffee (or tea) may be drunk only, or, more likely, a selection of baked goods such as doughnuts, cookies, slices of cake, or crackers will be available, too. These breaks are not only for eating and drinking but also for chatting.

In Great Britain, New Zealand, and Australia, people prefer a spot of tea during their tea break in the mid-morning or mid-afternoon, and later on at home, they have high tea in the early evening. High tea consists of a light, cold meal or baked goods, followed by a more substantial meal later in the evening. Tea breaks may be formal in homes, with a silver tray filled with tea cups on saucers, a silver bowl with sugar, and a silver pitcher with cream brought into a living room, dining room, or drawing room. Baked goods are also served at tea breaks. In both the U.K. and the U.S. as well as in other English-speaking countries, most people eat three full meals daily, but stopping for coffee or tea breaks has also become customary.

Another useful difference to understand between the British and American ways of life concerns traffic, which is of the utmost importance to travelers or visitors. In London, one takes the underground, whereas in New York it's the subway (whether or not traveling below the ground). Streetcars are taken in American cities, but trams are found in Britain. Make sure you fill up with gas at the gas station in Miami, but in Manchester you should top up the tank with petrol at the petrol station. Not sure whether you need oil? Check under the bonnet in Bristol but the hood in Houston. Check your wing mirror in Wales but your side mirror in Rochester. And watch out for those traffic circles in Tampa but those roundabouts in Reading.

It should not surprise anyone that British and American English are a little different grammatically (Americans say, “I don't have” and “I have a lot” but the British say “I haven't” and “I have much”). Their pronunciation and vocabulary also differ. These should not be sources of consternation when you visit different Anglo countries; instead, they should be occasions for adventure and enjoyment. Just as Mandarin-speaking foreigners can manage their way through the various dialects of Mandarin spoken in mainland China, so, too, should anyone versed in conversational English - of any stripe - succeed in having fun with the different worlds of English.


** Lesson 25 Earthquake Precautions

Bam! The bathroom door slamming against the wall woke me out of a sound sleep. Groggily wending my way in the dark to the bathroom, I secured the door latch to make sure I would have no further interruptions of much-needed sleep. I then lumbered back into bed and started to drift off.

Not for long. My body, the bed and the whole bedroom began shaking. After a few confused and frightening seconds, I realized “Earthquake!” “Big one,” I added, noting that the neighborhood dogs had joined in the weird sounds the hill around my house were making. Within moments I was out of bed and on my feet, contemplating leaving the house. “I'll wait,” I comforted myself. “Even these big ones pass in a few seconds.”

This one wouldn't. It kept coming; everything was shaking and trembling, rattling. I heard a pane of glass crash onto the floor. The walls of the house and the things attached to them seemed to heave, not just shudder. I then noticed that the street lights had failed and my heart was pounding harder than when I used to lift weights. I acknowledged my fear.

Realizing that there was no time to flee the house, I simply waited and waited. The nearly one-minute long temblor finally subsided, and my reasoning came back to me. All was well, or well enough. I walked unsteadily to another room and looked outside. A neighbor with a flashlight was checking on his and others' homes for damage.

I knew it had been a major quake, though not centered where I lived. The next day I learned that a 7.6 Richter-scale earthquake had devastated the lovely rural communities of central Taiwan. For the next few weeks, everyone's life was centered around the quake due to the constant media coverage and electricity rationing.

Taiwan is but one of many places situated along the “Ring of Fire” encircling nearly half the globe around the Pacific Ocean. Constant volcanic and earthquake action occurs here, sometimes with cataclysmic results. In this century alone, major earthquakes have taken more than one million lives. Many more have been injured and made homeless. The economic, social, and personal costs are immeasurable.

Over the past quarter century, many countries in earthquake-prone areas have begun to educate their citizens on how to take appropriate precautions for earthquakes. The following list has been compiled from experience.

Before the earthquake:

Prepare an “earthquake kit” near everyone's bed; these kits should include drinking water, a flashlight with fresh batteries, and dry food.

Place an extra pillow, blanket, or quilt near the bed to be placed over the head during the earthquake and for warmth if trapped afterwards.

During the earthquake:

If possible, get out of the building you are inside of and into a clear area.

If escape from a building is impossible, get away from windows and doors; try to find shelter under structural beams or under any heavy piece of furniture, like a large table or bed.

After the major earthquake (remember that aftershocks will occur):

When shaking ends or subsides, turn off gas lines.

Leave the building (never use elevators) quickly but not in a panic.

If uninjured, be ready to assist rescue workers with information or labor.

When a Big One happens, there is little anyone can do. Then above contingency preparations, however, could make the difference between life and death.


** Lesson 26 Berries: Nature's Natural Desserts

The last child has left the house for school. The table is clean and neatly set, and the coffee is brewing. The cool orange juice stands like a sentry over the tableware. Mother sits down, pours cereal into a bowl, and sprinkles it lightly with sugar. She is then ready for the final masterpiece. She carefully spoons precut ruby red strawberries onto the mound of golden corn flakes. Pouring ivory-white milk over the concoction, Mother smiles to herself. An attractive, nutritious breakfast fit for a queen.

Most people around the world are now familiar with and can enjoy strawberries, but few are familiar with other more exotic berries, such as the gooseberry, blackberry, and raspberry. Indeed, even fewer people realize what the word berry technically refers to. The berry of the botanist and the berry of the public are often two quite different fruits.

Those whose specialty is plants define a berry as a simple, fleshy fruit with a thin wall and many seeds. Under this classification are several surprises. One would expect that cranberries are berries, of course, but less obvious members of this class are dates, grapes, tomatoes, and even potatoes, bananas, and asparagus! Indeed, according to botanists, some popular "berries" are not true berries at all. Experts in plant life consider the blueberry an "inferior berry" and the strawberry, raspberry, and blackberry an "aggregate fleshy fruit". However, no matter how scientists call them, most people think of berries as small, round, sweet, and delicious fruits.

Berries such as strawberries, blackberries, raspberries, and blueberries prefer cool and moist growing conditions. Though they rarely thrive in tropical conditions, they can be grown on the sides of taller hills and mountains there. Several species of wildlife forage for berries, the largest of these being the bear. Some smaller mammals and birds, too, enjoy berries, not to mention people. Wild berries are noticeably smaller than their domesticated cousins, but many people prefer the full, rich taste of freshly picked forest berries.

Besides being a condiment of breakfast cereals, are there any other uses for berries? Westerners make good use of their local fruits. Jellies, jams, and preserves can be easily made with berries, gelatin, and sugar. These three sweetened foods differ only in the process used to make them. Jellies are made from the juice of a fruit, jams from the thoroughly crushed fruit, and preserves from the partially crushed or cut fruit. They are all equally delicious!

Berries are also used in baked goods. Pies and tarts often contain berries as do many other pastries. These small fruits are also added into cakes and even breads, especially after drying. In addition, the concentrated juice of berries can be used to make cool summer drinks. Concentrated further, various syrups can be added to foods as diverse as pancakes and ice cream. As flavorings, they are often added to candies and chocolates. In Western cuisine, life would be less sweet and interesting without the humble berry.

For some people, though, berries are best eaten fresh. They say that after washing and refrigerating, simply place a generous portion of berries into a cereal bowl, add chilled milk, and top with sugar. Enjoy! As the season for berries is usually in the summer and fall, this snack or dessert really hits the spot. For those who do not live where berries grow naturally and plentifully, these natural dessert fruits can be enjoyed while visiting those area lucky enough to have them.


** Lesson 27 The Global Proliferation of English

Everyone knows that there are more speakers of Mandarin than any other language in the world. Just over one billion people speak Mandarin as their native tongue. Compared to the nearly four hundred million native speakers of English, there would appear to be "no contest". Yet, it is just as well-known that English, not Mandarin, is the international language. Given these statistics, how can this be? Looking more closely at these and other facts reveals how English has become the world's most widespread language.

The history of written Chinese goes back at least 4000 years, that of English little more than 1000 years. The language called English is actually a hybrid of Scandinavian and German tongues created by immigrants to England in the 5th century A.D. Over the next 500 years, English developed into several major dialects spoken principally on most of the island of England. With continuous invasions by more Scandinavians and the French over the next few centuries, the English language received a fresh stimulus of foreign words, including Latin and Greek, the preferred classical languages in educational and political circles at that time in Europe. English as a principal language of literature did not evolve until the 14th century (Chaucer). By the 16th century, English was in full bloom, both in literature as well as in science.

England, referred to as Great Britain by this time, was amassing political, economic, and military power at breath-taking speed. The Industrial Revolution of the next century required foreign resources; imperialism gave the go-ahead for Britain and other European powers to not only take what they wanted from foreign lands but to lay conquest to those lands as well. Additionally, the rapid social changes engendered by the change from agriculture to manufacturing meant a surplus of farm workers, resulting in a waiting army of the dispossessed to emigrate to Britain's newfound colonies. In the 17th and 18th centuries, millions of Englishmen left their mother country for North America. In the 18th century, hundreds of thousands more set sail for Australia and New Zealand, as well as South Asia (the British Raj) and Africa (primarily South Africa). At the height of the British Empire, one-fourth of the world's people and lands were living under the Union Jack. Thus, by the close of the 19th century English rule had extended to the six principal continents (including British Guyana in South America).

This first-ever domination of the globe by one language is the primary reason for the international use of English today. A second reason lies in the rise of the United States of America as a leading world power just as Britain's power began to fade. At the close of the 19th century, the US fought with Spain (in 1898). After the US victory, Spain ceded the Philippines, Guam, and Puerto Rico, resulting in the further introduction of English into Asia and the Caribbean. After US involvement in both World Wars, despite Britain's continued decline, English became more commonly used around the world, especially in continental Europe and Japan. Since 1950, the rapidly growing U.S. economy as well as its academic and scientific excellence has insured that English remains the language of commerce and intellectual intercourse. The world of entertainment, most notably Hollywood, has also contributed to the popularization of English.

It is estimated that at least 300 million people around the world are now studying or using English as a second language, for purposes of education, employment, or personal interest. Some 75% of all international communications are in English, and with the rise of the Internet, it is doubtful that this figure will decrease any time soon. At the dawn of the new millennium, the world has one international language, English.


** Lesson 28 Tips on English Body Language

Mr. Garcia, a businessman from Madrid, Spain, is speaking English to one of his customers, Mr. Patton, from Vancouver, Canada. As they speak, a bystander notices that as Mr. Garcia slowly steps closer to Mr. Patton, the latter slowly steps away. This slow dance continues throughout the conversation until Mr. Patton is literally against the wall. He now crosses his arms in front of him. Mr. Patton appears nervous and a little annoyed; Mr. Garcia, aware of this, thinks he is not explaining himself well enough in English, even though Mr. Patton fully understands him. Thinking the business deal has gone sour, Mr. Garcia excuses himself and leaves.

What is going on here? If Mr. Garcia or any other non-native English speaking businessman, student, immigrant, or tourist had been aware of English body language, this unfortunate incident could have been avoided. Among English speakers, personal space is very important; indeed, personal space is important in all languages, but the distance considered critical to trigger discomfort differs. Spanish speakers tolerate a much closer speaking distance, a distance of some 30 centimeters, which is about half that which English speakers prefer. Thus, a Spanish Speaker will instinctively move in closer to talk with an English speaker, who instinctively moves away, closer to his preferred speaking distance.

Body language is one kind of nonverbal communication, such as winking (to indicate "I'm kidding" or a sexual advance), or arms held akimbo (in some cultures, merely resting; in others, a threatening or defiant stance). This communication can, on occasion, be even more important than the actual words spoken.

Take winking for example. In most cases, English speakers will wink (the closing of only one eye) at each other to show that they are not serious about what they are saying. They may also cross their middle finger over their index finger to indicate the same thing. These gestures are extremely important as they virtually negate what the speaker says.

Another example is eye contact. In many American Indian and East Asian cultures, respect is shown by not looking directly into the eyes of a person considered of a higher social class than oneself. For Western Europeans, the opposite is true. For them, anything less than full eye contact is considered disrespectful or even devious. Problems have arisen when Chinese or Korean school children enter American or European schools. Western teachers assume that these children are "up to something" or that they are showing disrespect, when, in actuality, they are behaving correctly for their own culture. One Chinese child was denied entry into a gifted students' school because he was considered "lacking leadership qualities" despite his overall excellence in his academic and interpersonal relations. When it was pointed out that Chinese children are taught not to be aggressive (show leadership qualities) the school reconsidered and admitted the lad.

Sometimes gestures used in different languages have contrary meanings. This can produce a humorous effect. In Vietnam and China, the gesture for "come here " is quite similar to that of waving "good-bye" in English. Thus, when speakers of these two cultures are leaving each other, if the English speaker gestures "good-bye", the Far Eastern speaker may misinterpret the signal as meaning, "come back here."

Learning body gestures is rather difficult from textbooks. The best way to learn gestures---for any language or culture--is to stay a while in a foreign country to learn not only what people say but how they say it. For most people, the learning of body language is an exciting and charming aspect of learning a foreign language.


** Lesson 29 The Fundamentals of Public Speaking.

What is the most terrifying experience for most people? Is it drowning? Is it falling from a high place to their death? Is it being attacked by wild dogs? Though these experiences would certainly frighten most people, according to a recent poll, most people fear standing on a stage in front of a group of people to deliver a speech more than anything else, including the above life-threatening scenarios! What is going on here? Why is public speaking so menacing to most people?

Coaches of public speaking are fond of noting that public speaking "is an unnatural act." This is a tongue-in-cheek definition. Though people usually think of kinky sex as an "unnatural act" public speaking is in one important way unnatural. Human communication is inseparable from the human condition; that is, we actually spend more time in communicating with others (including listening to prerecorded spoken information) than we do anything else except breathing. There is, in other words, nothing unnatural in communicating. Standing on a stage in front of a group of people to deliver a speech, however, is certainly unnatural. In no other situation do so many humans have to keep quiet, watch the speaker attentively, and keep their minds on the message without an opportunity to respond. In no other situation can one speaker command the silence of an entire group of people. The responsibility on both sides is taxing; hence, the very act of speaking in public breaks the natural rules of human discourse and is thus unnatural.

The result of this unnatural act is to make both the speaker and the audience somewhat nervous in their new roles as dominant speaker and submissive audience. Most people do not understand the mechanics of crowd control or public speaking and are terrified by even the notion of appearing alone in front of what many perceive as a hostile group of people. Actually, the audience should be pitied, not the speaker. Who wants to sit through a long, boring speech? Who wants to sit and have to listen, without the chance to respond to the speaker? Accomplished public speakers learn to accept that tension between the audience and the stage and work with it. These savvy speakers have some tips for novice speakers.

An obvious suggestion is to be well prepared. Though it is not a good idea to write out a speech and memorize it (this is a recitation, not a speech), preparing an outline of the main ideas of the topic in logical order is. Further, practicing the speech out loud will help the speaker identify the strong and weak parts of the speech.

Another good idea is to face the audience. The audience, after all, is the object of the endeavor. By noting their expressions, a speaker can often monitor whether he is speaking loudly enough, too quickly or slowly, at too difficult a level, etc. "Sweeping" the audience with one's attention ---looking at all sections of the audience at one time or another and regularly---helps the audience keep its attention focused on the speaker.

The most important of these suggestions, however, is simply to be sincere. The 16th president of the United States, Abraham Lincoln, said, "You can fool some of the people all of the time. You can fool all of the people some of the time. But you can't fool all of the people all of the time." These profound words are applicable to speakers in public. Since the audience is observing and listening to the speaker closely, it is virtually impossible for a speaker to fake sounding confident if he is not, nor is it possible for the speaker to convince an audience of his conviction if he himself is not convinced.

Following the simple tips listed above will improve a speaker's performance in public. Like any other skill or art, the more one practices, the better he is likely to become. Public speaking is not only for speech contests; all professionals must present themselves in public sooner or later. Rather than shirking the opportunity to speak, seize it and make the most of it the next time fortune knocks.


** Lesson 30 New Orleans: Birthplace of Jazz

Welcome to Crescent City, birthplace of jazz! "Crescent City?" Yes, the nickname for New Orleans is Crescent City, due to its downtown location along a particularly deep bend of the Mississippi River. No matter what this unique American city is called, New Orleans has something for everyone.

To understand why this southern city is so different from any other city of the United States, and perhaps also how it evolved the musical form of Dixieland jazz, it is necessary to give a brief description of its history. Founded in 1718 by French developers, New Orleans grew rather slowly. Although ideal for shipping (New Orleans is only 180 kilometers from the mouth of the Mississippi, the world's fourth-longest river), the land around New Orleans is extremely low-lying (the city is actually below sea level!) and was at that time nothing more than a swamp. Despite this, the city attracted a wide range of peoples, including Canadian and European French, slaves, American Indians, and a few white British settlers. The area's continued slow growth, however, convinced France that it should sell all of its extensive land holdings in North America to Spain in 1763. Spain ruled this large area including New Orleans until 1800, when the whole area was again returned to France, only to be sold to the US in 1803. The early French and Spanish cultures have remained with the city, even with the approach of 200 years of American rule.

The fortunes of New Orleans have always depended on its riparian location. The city gained importance in the War of 1812 and later as the terminus for shipping along the Mississippi through the Civil War. As shipping declined in importance due to the building of the railroads near the end of the 19th century, however, the Golden Age of New Orleans wound down. At this time, however, an artistic creation particular to New Orleans would resuscitate the city's fortunes.

Music has always played an important part in the daily lives of most Americans, and New Orleans happened to be home to some of the best musicians in the country. From 1880 to World War I, New Orleans with its cafe and night club society became host to a new form of music based mostly on the blues, but also on marches and ragtime music. In this style of music, the trumpet, clarinet, and trombone form the basis of instrumentation. As the trumpet is the loudest, it normally carries the melody, with the clarinet and trombone improvising above and below the trumpet, respectively. Sidney Bechet, Buddy Bolden, King Oliver, and most famously Louis Armstrong became symbols of the New Orleans red light district, and later to fans in music halls all around the world.

Though Dixieland jazz is today a preserved form of music like classical music, it later spawned Big Band music popular until the end of World War II, and urban jazz, still popular in the US as well as in other countries. To hear the original Dixieland jazz one has only to book a hotel room in the Vieux Carre district of New Orleans anytime of the year. The French and Spanish architecture and laid-back lifestyle there is the perfect place to enjoy the upbeat but relaxing sounds of Dixieland jazz. Devotees of jazz pack Preservation Hall, Dixieland Hall, and the night clubs along Bourbon Street to hear their favorite songs. The New Orleans Jazz Club stages many jazz events, as does the city government, such as the International Jazz and Heritage Festival. If you can visit New Orleans only once in your life, though, save it for the world-famous Mardi Gras. You can then enjoy the best of New Orleans's night life with as many as one million other party revelers!

The city of New Orleans has so much to offer. Its history, unique cultural blend including world-acclaimed cuisines, and, of course, its musical gift to the world, Dixieland jazz, are reasons enough to place New Orleans high on everyone's "must list" of places to visit. Whether you want to travel to relax or join in spirited partying, New Orleans offers the tourist the best of both worlds.


** Lesson 31 The Fine Art of Giving

Ralph is all excited. When his poor wife Lisa comes home after a hard day's work in the office, he enters the living room beaming. "Happy birthday, darling!" he exclaims while thrusting the neatly packed gift at her. Momentarily delighted as she quickly unwraps the package, Lisa murmurs, "Oh, Ralph, I thought you'd forget my birthday again this year. Gee, thanks, sweet..." Her voice trails off as she lifts the cover of the box to disclose its contents: steak knives. Ralph, still beaming, then pulls the trigger of the rifle aimed at his own foot: "I bought some steaks, so you can use your new birthday gift to get us dinner ready!"

Most women, of course, would use the new knives on Ralph, not the steaks. What did poor Ralph do wrong? He certainly meant well. He noted his wife's birthday carefully, sacrificed time and money to buy a gift on time, and even had the box gift-wrapped. Where did he go wrong? Long before Ralph bought the knives, he should have paid more attention to those things Lisa expressed or showed an interest in. While walking or shopping, many people notice things that obviously interest them; this is the time to make a mental note of what those items are for future purchase. While talking, too, many people reveal "wish list" items they dream of having. Noting these items and turning them into gifts at a later time, whether for Christmas, birthday, anniversary, graduation, or any other important occasion, distinguishes just another item on a shelf in a department store or in a catalogue from "the perfect gift".

Gifts do not have to be objects. Doing house chores for parents or spouses which normally are "theirs", taking someone out on the town or wheeling an invalid around the block, or taking the time and effort to create one's own personalized handicraft can bring smiles as wide as those aroused by the giving of expensive presents. Many a child would prefer to have an afternoon at the cinema and an evening in their favorite restaurant with Dad than another of his expensive gifts, some with the price tag still on them! Many parents would rather happily settle for a full day with their children at home or on a picnic than with a mailed check or "Happy Birthday" greeting on their answering machine. Perhaps the expression "Time is money" really is true: time spent with those whom we do not often see is indeed precious. Sacrificing time from one's busy schedule to give to another is often more meaningful than a pricy gift from an upscale department store.

Of course, there is nothing wrong with buying gifts. Everyone has needs, including material needs. Close friends or family members often know what their loved ones need even before they do! Few compliments can make us happier than "you always know what to give me". For those who never seem to know what to prepare for others but who would like to learn, observing the successful giving of gifts to others is as good a place to start as any. In any class, family, or crowd, someone always seems to know the right gift to give at the right time. Making mental notes of these occasions and then writing them down in a special notebook can make the difference between a future present well-received and one politely accepted.

Still, only a social incompetent would criticize or refuse a gift from another. Being gracious even in disappointment is a sign of good manners. Besides, a gift is an expression of thoughtfulness and a token of love. We should never question the judgment of the donor; instead, as we say in English, "It's the thought that counts". Learning to appreciate whatever little surprises life prepares for us is a sure sign of maturity and poise. When the giving of symbols of our appreciation and love to others becomes an art form to the giver, these profound words can be understood: "it's more blessed to give than to receive."


** Lesson 32 Professional Telephone Etiquette

"(ring...ring...ring...) Hello?"
"Un, excuse me, but is this Dragon Mountain Trading Company?"
"Who's calling?"
"Well, I'm Mr. David Parker, and I..."
"What do you want?"
"I'd, uh, like to speak with your manager."
"He's busy. Call back later. (click)"

Unfortunately, some companies still have not trained their employees in the professional use of the telephone. The above telephone conversation is not only discourteous, but also hurts business prospects. If Mr. Parker is calling to speak with a number of companies in order to build business relationships with them, he is not very likely to call Dragon Mountain Trading Company again. To prevent this from happening, those who are responsible for the conduct of business over the telephone should keep a few simple but important points of telephone etiquette in mind.

The first and most important point concerning the professional use of the telephone is the attitude towards any caller. The telephone is the lifeline of the company with the outside world, and those who call in should be considered potential business prospects. However, customers are not nameless, faceless voices; they are people who enjoy being and deserve to be treated courteously and fairly. Everyone who uses an office telephone should remember that a friendly, helpful, and efficient call can make the difference between success and failure with the caller. Once this is appreciated, a business office can operate at its full potential.

How can all office workers put the above principle into practice? Several tips on the successful use of the office telephone have been collected from many companies over the years. This advice is timeless and covers all manner of businesses. Companies whose employees use the following telephone etiquette are more likely to keep their clients and attract new customers.

When answering the phone, all employees should identify the company and themselves. In the above hypothetical conversation, the office worker should have answered the call with, "Dragon Trading Company, Janice Wang, speaking." rather than force Mr. Parker to inquire whether or not he had dialed the company telephone number correctly. In some companies, employees will further identify their position within the company, such "Kodak, Michael Chou, sales representative, speaking." or "Great Light Sports Equipment, Frances Chang, personnel director, speaking. May I help you?" and so on. Of course, in larger companies which have automated dialing or an operator, it is often unnecessary to state the name of the company (that has been done already on the tape or by the operator), but self-identification continues to be helpful, and, thus, important.

As with Frances Chang above, a simple "May I help you?" is enough to invite the caller to state his or her business with the company. However, it is always important to listen carefully to the caller's request. It is possible, for example, that the callee is not the right person for whom the caller is looking; by listening carefully, the callee can respond to the needs of the customer on the line. Treating caller as routine or even annoying interruptions to one's work is a mistake. If someone outside the company has taken the time to call in, someone inside the company should take the time to respond to it.

If the caller is looking for someone not presently in the office, a message should be taken and then repeated over the phone to make sure all the information is correct. If a product or service is unavailable, the caller should be told what possible substitute is available or when the desired item will be back in stock. every effort should be made to please the caller. This extra effort makes a lasting impression, the kind of impression that often results in repeat business. In our conversation above, the callee should have told Mr. Parker when the manager would return to take his call, or offered to take a message for him. Hanging up on the caller is the best way to lose business.

After information has been given or help offered, the call should not be considered finished. Each call is an opportunity to further the interests of the company, as with "We have other fine products. I'd be happy to send you our catalogue." or "Our company can offer additional service. My manager or I would be happy to make an appointment with you to discuss them." above all, end each conversation with a genuine. "Thank you for calling. It's been a pleasure serving you." or other lines to make the customer feel he or she is not being discarded as just another business obligation. Successful calls make customers feel welcome to call again.

Today's world of business is highly competitive. People have not changed, however. They still like to be treated in a friendly and helpful way, even over the telephone. A genuinely friendly and helpful attitude on the phone, identification of company and callee, offers of help or message taking, promotion of further business opportunities, and leaving the caller with the feeling that he would like to call again seem like insignificant matters. Added up, however, they can make the difference between a company's success and failure in our high-tech but still human world.


** Lesson 33 Did you Remember your Tickets? 

Robert and Michael leave their apartment in a rush and find a taxi to take them to the airport. After paying the driver, Robert turns to Michael and says, "That was close! I thought we'd be late for sure. Come on, now, we have to take our luggage into the terminal and check in at the counter." "Right," responds Michael, "did you bring the tickets and our passports?" "No," answers Robert, "I thought you did!"

This scene could be from a TV sitcom or real-life. Every traveler's nightmare is forgetting something major like tickets, ID, passport, or money. This is needless worry, however, if travel plans are made early and organized efficiently. Since travel for education, business, or pleasure is more and more common, knowing how to prepare for worry-free travel is both important and beneficial. This lesson will help the novice or experienced traveler avoid potential travel problems, allowing for a pleasant journey.

Unless there is an emergency, travel plans should be made well in advance. Never wait till the last minute to try to reserve airline tickets or hotel rooms. They may not be available, or you may be forced to choose an inconvenient or unnecessarily expensive flight or accommodation. The best day to book travel or lodging arrangements is the day you decide to go.

After all travel arrangements have been secured, then next step is to make sure your travel documents are in order. Is your passport valid? Remember that some countries do not accept passports which have less than six months' validity remaining. Do you need an overseas driver's license? These can be applied for at certain government or travel agencies or associations. Leave enough time to process any paperwork that is required. A travel agent or experienced friend or colleague can inform you of what steps need to be taken and how best to take care of them.

Preparing for packing is next. Even if the proposed trip is a month away, certain items should be readied at once. The most important of these is, of course, the luggage itself. Do not wait for a last-minute sale on the suitcase of your choice; be ready with enough good-quality luggage long before you leave for the airport or train station. In choosing baggage, make sure that it is within regulations, especially for air travel. Oversize suitcases or carry-on baggage can be a great headache later.

The rule of thumb for packing is pack less, not more. Most travelers buy at least some items on the road, and some buy quite a few souvenirs or personal items, so leave enough room for them. Keeping a toiletry kit permanently in a piece of luggage is a smart idea. In this way, you will never have to worry about whether your razor or deodorant has been packed. Casual clothing, including footwear, should be placed into bags or suitcases the night before. Formal wear can be packed in the last-minute to reduce wrinkling. Don't worry about taking reading or writing material for pleasure; newspapers and magazines are widely available, as is stationery.

The day before leaving, reserve a cab for the day of departure if needed. This is also the best time to ask a friend or relative for a wake-up call for those leaving early on the day of departure; this is even better than one's own alarm clock. Leave a copy of the itinerary with lodging telephone numbers with a family or friend. Place all travel documents into one briefcase or folder rather tan in several places for ease of checking. After packing each piece of luggage, put it near the door for easy exit. These simple advance steps will help reduce stress on the day of travel.

On the day of departure, the only steps remaining should be to pack one's formal clothing and to recheck one's travel documents and money. Whether for business, education, or pleasure, travel can be an unforgettable experience. Whether you want to remember that experience fondly or try to forget it depends on the few simple steps outlined above. Bon voyage!


** Lesson 34 English Small Talk Topics: What is OK and what is Not? 

"When in Rome, do as the Romans do." What may be perfectly acceptable to talk about in one culture may offend or even shock others when in a different culture. Accordingly, it is important to know what topics are "safe" to discuss with strangers or acquaintances from a different background. Topics which can be discussed freely within a culture are referred to as "small talk".

As with any other language, English has its own stock of non-offensive topics. Among these are the weather, occupation, immediate conditions, family and family life, and school or work. Topics in English which should never be broached include one's personal life, physical appearance (unless complimentary), income, and age as well as religious, sexual, or political views. Each of these topics---both approved and taboo---will be discussed in more detail later.

Small talk is extremely useful when first meeting others. Actually, one purpose of small talk is not to find out the answer to questions like "How are you?" or "Nice day, isn't it?" but rather to gauge whether the person is the sort whom one would like to know better. While talking about essentially unimportant matters such as the weather, life in the office, or how many children---if any---one has, each speaker has the opportunity to determine whether the other is cooperative, interesting, potentially useful or friendly, etc. If a person answers the inquiry about the weather with a grunt or "I hate sunny days," no further energy need be wasted!

Another purpose of small talk, once a speaker is satisfied that the other person is worth talking with, is to explore possible areas of interest or cooperation. By tactfully going through "safe topics," some information may be revealed which leads the speaker(s) into a deeper discussion, especially when a topic is a shared hobby or interest. Talking about the weather may reveal that one speaker enjoys recreation like camping or hiking. Shooting the breeze about one's family may disclose similar shared family hobbies like board or card games or barbecues and picnics. In other words, small talk may serve as probing of the other person's personality and lifestyle.

"Everybody complains about the weather, but nobody ever does anything about it," so goes an old saying. Perhaps the safest of all small talk topics is the weather. Whether good or bad, a comment about the temperature or sky condition (sunny day, cloudy day, rainy day, etc. ) never offends. Commenting on the crowded traffic or the late bus, or high prices in the department store (immediate conditions) is also always appropriate. Similarly, most people do not mind talking about their work, family, or school life, either, since for most people these are experiences held in common. Even so, asking whether someone is married or not crosses over into personal information and therefore should be avoided. If the speaker happens to mention that he or she has children or is married, however, it is all right to pursue the topic.

Asking such questions as "How much do you weigh?" "How old are you?" or "How much do you earn?" are taboo in English, at least as starters for conversation. Only when friends are close would they ask such questions of each other. Likewise, for most people, religious or political convictions or sexual mores are considered private matters. These should not be discussed until one speaker offers his opinion first. It is not necessary, though, to respond in kind. The other speaker can change the subject to show that this is a taboo subject.

Foreigners are usually "forgiven" the "indiscretion" of asking others offending questions. Still, it is not a good idea to wear out one's welcome. When a subject has been turned down, only a tactless person would pursue it. Being sensitive to others' feelings and sense of privacy will win more friends and influence more people than a reckless line of questioning. When curiosity seems to be getting the upper hand, remember that "Silence is golden."


** Lesson 35 Hot Animals Around the World: The Panda

Some countries have adopted an animal as a kind of national mascot. The bald eagle is often thought of as representing the United States, for example. New Zealanders proudly display their kiwi, a native flightless bird. Australians cannot seem to make up their minds whether the koala or the kangaroo should represent them. China also has two animals which often stand out in everyone's mind: the dragon and the giant panda. As the dragon is a mythological animal, that leaves the giant panda as the only real animal representative of China.

Although dragons have been associated with China for thousands of years, the panda's inclusion into the Chinese psyche is far more recent. The giant panda was not even discovered until 1869; it was already a rare animal at that time, living in the high bamboo forests of Sichuan province and neighboring parts of Tibet. Its more plentiful cousin, the lesser panda, is also referred to as the cat bear or bear cat; however, zoologically speaking, it is neither. The lesser panda is a member of the raccoon family, whereas the giant panda's classification is still a dilemma: some authorities consider it a member of the bear family while others maintain that it belongs to the raccoon family, too.

The giant panda is well named. Reaching a length of 1.5 meters and 160 kilograms, this gentle omnivore is among the largest land animals of China. Subsisting on a diet of bamboo and other plants, and even small animals, it can consume as much as 30 kilograms of food a day. Now that's a giant appetite! Its distinctive markings--broad, white bands of fur alternating with black, and small black circles around the eyes--have endeared the giant panda to animal lovers everywhere.

People may want to hug this huge "teddy bear," but giant pandas prefer to live a solitary life. This may account for their scarcity; these pandas are on all official lists of endangered animals. Estimates of the wild panda population are difficult due to the rugged terrain they live in, but most experts agree that fewer than 1000 remain free. As they give birth to only one or two cubs when mating is successful, the giant panda's survival in the wild is anything but a foregone conclusion. The Chinese government has set aside 11 nature preserves where pandas are known to exist, hoping to protect them from the rapid encroachment of man. Though poaching is still a problem, strict laws have reduced this senseless carnage.

Pandas in captivity number less than 100, the largest share, of course, in China. Those in Western zoos are treated as royalty and are the object of intense scientific interest and care. Recently, veterinarians have given male giant pandas Viagra, hoping to increase the animals' reproductive efficiency. Results are thus far inconclusive. Though births have been reported, they are few and far between. It seems the panda's chance of survival is razor-thin.

Its extinction would be a sad day for all of mankind. These playful and gentle creatures never fail to amuse adults and children alike lucky enough to observe them in zoos. Every plant and animal that leaves the world due to human intervention and encroachment of habitat diminishes the world we live in. The richness of the Earth's original biodiversity is being attacked. Will future generations of humanity be left with only a few species of food plants, and zoos exhibiting cockroaches and rats?

Hopefully, men will learn the excesses of their ways and strive to protect the remaining natural habitats as an investment not only in the flora and fauna remaining but in the quality of life present and future, of all those on this planet. "Extinction is forever" and "There is only one world" need no longer be heard if everyone becomes conscious of preserving the beauty of the natural world around us.


** Lesson 36 Vancouver: Asia's Newest City

What? Wait a minute! Did I read that right? I thought Vancouver was in Canada, not in Asia. Why is the title of this article "Vancouver: Asia's Newest City"?

Relax, everyone. Yes, Vancouver is still in Canada, North America's largest country, not in Asia. Over the past twenty years, however, Asians from China, Taiwan, Hong Kong, Thailand, the Philippines, and other countries across the ocean have flocked into this largest city on Canada's Pacific coast. By some accounts, as many as 30% of households in Vancouver speak Mandarin or Cantonese, making the Chinese there the largest minority by far. Just what is the attraction of this English-speaking city, however?

A visit to Vancouver quickly reveals her charms. Situated on the ocean and possessing a fine, deep-water port, British Columbia's largest city faces Vancouver Island to the west and mountains to the east and north. Most of the city is relatively new, having been rebuilt after a great fire in 1886. The completion of the Panama Canal in 1915 during World War I helped spur growth all along the West Coast of North America, as products from the western states of the United States and the western provinces of Canada could be profitably shipped to Europe. By the 1930s Vancouver had become Canada's third-largest city, a position it maintains today. Lumber from the extensive forested areas within the province, minerals, seafood, and assorted industries. including tourism, give the million-plus residents of metropolitan Vancouver a high standard of living.

The city itself is comfortable and attractive. A large central park called Stanley Park includes a zoo, gardens, arboretum, and aquarium! The University of British Columbia and Simon Fraser University are located in the greater Vancouver area, as are many small and quaint farming and fishing villages within a few hours' drive. Scenic, unpolluted, and prosperous: who could ask for anything more?

Certainly not the Chinese. Although limited immigration from the Far East began as early as the 19th century, it was not until the 1970s that immigration to both Canada and the United States began to increase significantly. By the 1980s, the steady stream had become a flood. Today, Vancouver's Chinatown is said to be North America's second largest. Given the large numbers of Chinese living in the much larger cities of New York, Toronto, Los Angeles, and San Francisco, that represents astronomical growth.

Vancouver's Chinatown is located within walking distance of the downtown area, as are most Chinatowns in North America. Here one can find both traditional Chinese herbal stores and fresh food markets as well as small retail and service businesses. From mid-May to September, Friday to Sunday evenings from 6:30 to 11:30, both Chinese and "foreign" visitors to this area might mistake themselves as being in Shanghai or Hong Kong. For daytime visitors, the Dr. Sun Yat-sen Classical Chinese Gardens is a must, offering beautifully landscaped floral gardens. The nearby Chinese Cultural Center conducts walking tours of the historic district and even a slide show revealing the historic development of the area.

Of course, Vancouver has much more to offer its residents and out-of-town and overseas visitors. Though--or perhaps because--it lacks the manic energy of East Coast cities of North America or those of modern Asia, Vancouver continues to attract new residents with its serene, safe, and, well, sane lifestyle.



** Lesson 37 The Germanic Languages

Most people have heard of the Tower of Babel story in the Bible. According to this story, long ago all people spoke the same language. Later, however, they were punished by speaking a great number of different tongues. Today, there are literally thousands of different languages (defined as mutually unintelligible tongues) around the world, though many are related to one another. Indeed, the two largest language families, the Indo-European (the language family with the largest number of speakers) and Sino-Tibetan (containing the Chinese languages, Thai, Vietnamese, and Tibetan) include hundreds of languages with over half the world's population.

Because there are so many languages within the above two super-categories of language families, linguists have further divided these linguistically rich and geographically diverse families into subgroups, one of which, the Germanic language group, has the second-largest number of speakers (Chinese being first). Within this group of over 500,000,000 speakers is the world's foremost international language, English, foremost in terms of its geographic spread and number of second-language users. German, spoken by just over 100,000,000 people, is one of the world's ten-largest languages in terms of population. As English and German speakers constitute the majorities in several of the world's most economically, militarily, and technologically developed countries, it is important to be familiar with this particular language grouping.

Linguists further divide the Germanic languages into three groups, two extant and one extinct. East Germanic languages are no longer spoken; Gothic is an example of this small and historic grouping. Afrikaans, Dutch, English, Flemish, and German are the more important languages within the West Germanic grouping. The Scandinavian languages of Danish, Icelandic, Norwegian, and Swedish comprise the North Germanic grouping. Though these languages cannot be easily understood among their different speakers, the similarities in vocabulary are striking.

Take for example the two largest languages with this group, English and German. The word Haus in German is house in English, with nearly the same pronunciation. Some names of German family members are instantly recognizable to English listeners and readers: Mutter, Bruder and Onkel for the English mother, brother and uncle (all German nouns are capitalized in print). Other German family members are easily learned: Vater, Schwester and Tante for the English father, sister and aunt. Thus, those who know English and want to study German find their first year of learning vocabulary to be relatively easy. The same is true, of course, for those who want to learn Dutch or Danish from an English or German background; these many similarities are due to the single common parent language of all the Germanic tongues, even though this "grandfather" language no longer exists.

Speakers and writers of the Germanic languages account for a great deal of the world's output in everything from economics to literature to military to science and technology. Hardly an aspect of modern life does not benefit from the contributions made by those using these languages, as in the Internet, Hollywood entertainment, Dutch (Phillips) and Scandinavian consumer goods design (Ericsson, maker of cellular phones, is a Swedish company, as are Volvo and Saab), and even the Nobel prizes (awarded by both Norwegian and Swedish institutes). More than one-third of the world's economic production originates in these countries, too.

For any speaker of a language outside the Germanic language group preparing to choose a useful second language for the future, English is probably the best bet. German, too, is very useful in the fields of medicine, economics, military, and science and technology. Being able to communicate with others in this far-reaching linguistic group will offer the user immeasurable benefits.


** Lesson 38 Learning How to Apologize

What are the hardest words to pronounce in English? It seems that "I'm sorry" are the two most difficult words for most people to say. Perhaps this difficulty lies in the so-called "losing of face" phrase; when a person apologizes, he lowers himself before another. Yet no one is perfect; everyone makes mistakes. After making a mistake, people should apologize to set things straight with others.

Two phrases in English often confuse non-native users of this language. These phrases are "I'm sorry" and "Excuse me." The latter is used to ask for information, as in "Excuse me, (but) do you have the time?" or "Excuse me, (but) can you tell me whether there is a post office near here?" "Excuse me" is also used when it is necessary to disturb others, as when one person interrupts two others speaking: "Excuse me for interrupting, (but) I have to leave now." Another example of the proper usage of this phrase is when, as a stranger, you want to point something out of benefit to someone, as in "Excuse me, (but) l believe you dropped something out of your wallet." Another common instance of using "Excuse me" is in crowded elevators, stores, or lines when a person needs to get through or get out. "Excuse me, (but) this is my floor" is a very handy phrase to learn when in crowded elevators. In all these cases, "Pardon me" may also be used; however, it is more often used in British than in American English.

When is "I'm sorry" used? For more serious incidents. Stepping on someone's toes on a crowded bus, though not intentional, should elicit an immediate "I'm sorry." Bumping into someone even on a crowded street where it is difficult not to also calls for "I'm sorry." Careless or late work in school or in the office requires our apology to teachers, colleagues, or employers. Being late for meetings or dates needs both an apology and often either a reason for the tardiness or an explanation of what course of action will be taken to eliminate any future possibility of recurrence. No one likes to be wronged, intentionally or otherwise. Saying "I'm sorry" can go a long way towards rectifying an awkward situation.

Even more importantly, saying "I'm sorry" is necessary when intentional harm has been done. The borrowing of an item without first informing the owner - who later discovers the "theft" - can be quite embarrassing. A simple but sincere "I'm sorry" might repair the damage done. Careless comments or insults which offend others may be ameliorated with that simple phrase, though sincerity in voice and gesture make all the difference. Similarly, young lovers, often exasperated in unrequited love, may purposefully hurt each other, only later to profoundly regret what they had done. At these times, a heartfelt "I'm sorry" may redress the pain of the one inflicted by love's arrows. Even better, "Please forgive me" may be used, as it is considered a stronger expression of remorse.

Learning to apologize in another language does not excuse speakers from practicing the same good manners in their mother tongue. So many people lament the coldness of modem society; human relationships have been worn thin from constant urban pressures. Part of this problem seems to be that people no longer use such simple words as "please," "thank you" and "I'm sorry." They cost nothing, but can bring a wealth of pleasure or relief to those who hear them. They require little effort, yet these few syllables can enliven someone else's day. So, why not use them whenever possible?


